#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.PortalIPS;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PortalIPS/Views/Category/CreateHtml.cshtml")]
    public partial class _Areas_PortalIPS_Views_Category_CreateHtml_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_PortalIPS_Views_Category_CreateHtml_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(" \r\n\r\n<!--左菜单-->\r\n<div");

WriteLiteral(" region=\"west\"");

WriteLiteral(" split=\"true\"");

WriteLiteral(" title=\"栏目树\"");

WriteLiteral(" style=\"width: 180px;\"");

WriteLiteral(" id=\"west\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"NodesTree\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n<!--主面板-->\r\n<div");

WriteLiteral(" id=\"mainPanle\"");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"padding: 10px;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"padding: 10px 0 10px 60px\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" id=\"ff\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(" action=\"\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral(" cellpadding=\"1\"");

WriteLiteral(" width=\"98%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n                <tr");

WriteLiteral(" class=\"mytr\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" class=\"mytd\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"javascript:expandAll();\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(">\r\n                            全部展开\r\n                        </a>\r\n              " +
"          <a");

WriteLiteral(" href=\"javascript:collapseAll();\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(">\r\n                            全部收缩\r\n                        </a>\r\n              " +
"          <input");

WriteLiteral(" id=\"chkCheckAll\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" onchange=\" selectAll() \"");

WriteLiteral(" /><label");

WriteLiteral(" for=\"chkCheckAll\"");

WriteLiteral(">全选/反选</label>\r\n                        <input");

WriteLiteral(" id=\"chkCascadeCheck\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onchange=\" jQuery(\'#NodesTree\').tree({ cascadeCheck: jQuery(this).is(\':checked\')" +
" }) \"");

WriteLiteral(" /><label");

WriteLiteral(" for=\"chkCascadeCheck\"");

WriteLiteral(">选中父级同时全选子级</label>\r\n                    </td>\r\n                </tr>\r\n          " +
"      <tr");

WriteLiteral(" class=\"mytr\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" class=\"mytd\"");

WriteLiteral(" width=\"100\"");

WriteLiteral(">\r\n                        生成列表页:\r\n                    </td>\r\n                   " +
" <td");

WriteLiteral(" class=\"mytd\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"chkCreateList\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr");

WriteLiteral(" class=\"mytr\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" class=\"mytd\"");

WriteLiteral(">\r\n                        生成内容页:\r\n                    </td>\r\n                   " +
" <td");

WriteLiteral(" class=\"mytd\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"chkCreateInfo\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n                    </td>\r\n                </tr>\r\n                <tr");

WriteLiteral(" class=\"mytr\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" class=\"mytd\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" height=\"30px;\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"javascript:GetChecked()\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"iconCls:\'icon-ok\'\"");

WriteLiteral(">\r\n                            生成\r\n                        </a> <a");

WriteLiteral(" href=\"javascript:CreateHtml_Show_TopN()\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"iconCls:\'icon-ok\'\"");

WriteLiteral(">\r\n                            生成最新100篇\r\n                            <a");

WriteLiteral(" href=\"javascript:CreateAllInfoList();\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"iconCls:\'icon-ok\'\"");

WriteLiteral("> 生成所有列表页</a>\r\n                    </td>\r\n                </tr>\r\n            </ta" +
"ble>\r\n            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"CategoryID\"");

WriteLiteral(" name=\"CategoryID\"");

WriteLiteral(" />\r\n        </form>\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var ResourcesPath = \"/Resources/\";\r\n        var nodeId = 0;\r\n        v" +
"ar model = \"Information\";\r\n        var _webUrl = \"");

            
            #line 60 "..\..\Areas\PortalIPS\Views\Category\CreateHtml.cshtml"
                   Write(Yamon.Framework.Common.ConfigHelper.GetConfigString("WebUrl"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        jQuery(function () {\r\n            jQuery(\"#NodesTree\").tree({\r\n      " +
"          lines: true,\r\n                checkbox: true,\r\n                cascade" +
"Check: false,\r\n                animate: true,\r\n                url: \'/api/Portal" +
"IPS/Category/GetMyCategoryTreeJsonAction?ShowRoot=1\',\r\n                onSelect:" +
" function (node) {\r\n                    if (node.checked) {\r\n                   " +
"     jQuery(\"#NodesTree\").tree(\'uncheck\', node.target);\r\n                    } e" +
"lse {\r\n                        jQuery(\"#NodesTree\").tree(\'check\', node.target);\r" +
"\n                    }\r\n                },\r\n                onLoadSuccess: funct" +
"ion (node, data) {\r\n                    jQuery(\"#NodesTree\").tree(\'collapseAll\')" +
";\r\n                }\r\n            });\r\n        });\r\n\r\n        function expandAll" +
"() {\r\n            jQuery(\'#NodesTree\').tree(\'expandAll\');\r\n            return;\r\n" +
"        }\r\n\r\n        function collapseAll() {\r\n            jQuery(\'#NodesTree\')." +
"tree(\'collapseAll\');\r\n        }\r\n\r\n        function selectAll() {\r\n            v" +
"ar check = jQuery(\'#chkCheckAll\').is(\':checked\') ? \'check\' : \'uncheck\';\r\n       " +
"     var roots = jQuery(\"#NodesTree\").tree(\'getRoots\');\r\n            for (var i " +
"= 0; i < roots.length; i++) {\r\n                jQuery(\"#NodesTree\").tree(check, " +
"roots[i].target);\r\n                var child = jQuery(\"#NodesTree\").tree(\'getChi" +
"ldren\', roots[i].target);\r\n                for (var j = 0; j < child.length; j++" +
") {\r\n                    jQuery(\"#NodesTree\").tree(check, child[j].target);\r\n   " +
"             }\r\n            }\r\n            // jQuery(\"#NodesTree\").tree(\"check\"," +
" jQuery(\"#NodesTree\").tree(\'getRoot\'));\r\n        }\r\n\r\n        function GetChecke" +
"d() {\r\n            var nodes = jQuery(\"#NodesTree\").tree(\"getChecked\");\r\n       " +
"     var s = \'\';\r\n            for (var i = 0; i < nodes.length; i++) {\r\n        " +
"        if (s != \'\') s += \',\';\r\n                s += nodes[i].id;\r\n            }" +
"\r\n            if (s == \"\") {\r\n                alert(\"请选择要生成的栏目！\");\r\n            " +
"    return;\r\n            }\r\n            jQuery(\'#CategoryID\').val(s);\r\n         " +
"   jQuery(\'#ff\').attr(\'action\', _webUrl + \"Default/CreateInfoList?CreateList=\" +" +
" jQuery(\'#chkCreateList\').is(\':checked\') + \"&CreateDetail=\" + jQuery(\'#chkCreate" +
"Info\').is(\':checked\'));\r\n            jQuery(\'#ff\').submit();\r\n        }\r\n\r\n     " +
"   function CreateHtml_Show_TopN() {\r\n            window.open(_webUrl + \"Default" +
"/CreateInfoTopN?top=100&CreateList=\" + jQuery(\'#chkCreateList\').is(\':checked\') +" +
" \"&CreateDetail=\" + jQuery(\'#chkCreateInfo\').is(\':checked\'));\r\n        }\r\n\r\n    " +
"    function CreateAllInfoList() {\r\n            window.open(_webUrl + \"CreateAll" +
"InfoList\");\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
