#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/ads.cshtml")]
    public partial class _Views_Home_ads_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_ads_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\ads.cshtml"
   ViewBag.Title = "ads"; 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n\r\n<head>\r\n    <title>s栏目管理</title>\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Home\ads.cshtml"
Write(RenderPage("~/Views/includeM/head.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Static/manage/js/checkfrom.js\"");

WriteLiteral("></script>\r\n</head>\r\n\r\n<body>\r\n\r\n    <div");

WriteLiteral(" class=\"place\"");

WriteLiteral(">\r\n        <span>位置：</span>\r\n        <ul");

WriteLiteral(" class=\"placeul\"");

WriteLiteral(">\r\n            <li>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 482), Tuple.Create("\"", 509)
, Tuple.Create(Tuple.Create("", 489), Tuple.Create<System.Object, System.Int32>(Href("~/Views/Manage/mains")
, 489), false)
);

WriteLiteral(">首页</a>\r\n            </li>\r\n            <li>广告位管理</li>\r\n        </ul>\r\n    </div>" +
"\r\n\r\n    <div");

WriteLiteral(" class=\"rightinfo\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"tools\"");

WriteLiteral(">\r\n\r\n            <ul");

WriteLiteral(" class=\"toolbar2\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"current\"");

WriteLiteral(">广告位管理</a>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n\r\n        <" +
"div>\r\n            <table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" class=\"cast_list\"");

WriteLiteral(">\r\n                <tr>\r\n                    <th");

WriteLiteral(" width=\"5%\"");

WriteLiteral(">栏目ID</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">栏目名称</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">栏目类型</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">数据量</th>\r\n                    <th");

WriteLiteral(" width=\"35%\"");

WriteLiteral(">管理操作</th>\r\n                </tr>\r\n\r\n                <tr>\r\n                    <t" +
"d");

WriteLiteral(" width=\"5%\"");

WriteLiteral(">6</td>\r\n                    <td");

WriteLiteral(" width=\"10%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">【首页轮播】</td>\r\n                    <td");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">广告列表</td>\r\n                    <td");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"35%\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"ad.php?pid=6&ty=54\"");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">广告管理</a>&nbsp;\r\n                    </td>\r\n                </tr>\r\n\r\n            " +
"</table>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n\r\n    </div>\r\n\r\n</body>\r\n\r\n</html>");

        }
    }
}
#pragma warning restore 1591
