#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Home\lefts.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    
    #line 2 "..\..\Views\Home\lefts.cshtml"
    using Yamon.Module.SiteManage.Entity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/lefts.cshtml")]
    public partial class _Views_Home_lefts_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_lefts_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Home\lefts.cshtml"
  
    ViewBag.Title = "lefts";
    Layout = null;
    List<Menu> menuList = (List<Menu>)ViewBag.LeftMenuList;
    string menuStr = RequestHelper.GetString("menuId");

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Home\lefts.cshtml"
Write(RenderPage("~/Views/includeM/head.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <title>网站信息</title>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(function () {
            //导航切换
            $("".menuson li"").click(function () {
                $("".menuson li.active"").removeClass(""active"")
                $(this).addClass(""active"");
            });

            $('.title').click(function () {
                var $ul = $(this).next('ul');
                $('dd').find('ul').slideUp();
                if ($ul.is(':visible')) {
                    $(this).next('ul').slideUp();
                } else {
                    $(this).next('ul').slideDown();
                }
            });

            
        });
    </script>
</head>

<body");

WriteLiteral(" style=\"background:#f0f9fd;\"");

WriteLiteral(">\r\n    <dl");

WriteLiteral(" class=\"leftmenu\"");

WriteLiteral(" style=\"height:100%; overflow-y:auto; padding-bottom:0px;\"");

WriteLiteral(">\r\n");

            
            #line 40 "..\..\Views\Home\lefts.cshtml"
        
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Home\lefts.cshtml"
         foreach (Menu menu in menuList)
        {
            string menuId = menu.MenuID;
            
            if (menuStr != menuId)
            {
                continue;
            }
            
            if (menu.Children == null)
            {
                
            }
            else 
            { 
                foreach (Menu subMenu in menu.Children)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <dd>\r\n                        <div");

WriteLiteral(" class=\"title\"");

WriteAttribute("url", Tuple.Create(" url=\"", 1752), Tuple.Create("\"", 1802)
            
            #line 58 "..\..\Views\Home\lefts.cshtml"
, Tuple.Create(Tuple.Create("", 1758), Tuple.Create<System.Object, System.Int32>(subMenu.LinkUrl.Replace("Frame=1", "1=1")
            
            #line default
            #line hidden
, 1758), false)
);

WriteAttribute("parentid", Tuple.Create(" parentid=\"", 1803), Tuple.Create("\"", 1821)
            
            #line 58 "..\..\Views\Home\lefts.cshtml"
                        , Tuple.Create(Tuple.Create("", 1814), Tuple.Create<System.Object, System.Int32>(menuId
            
            #line default
            #line hidden
, 1814), false)
);

WriteAttribute("menuid", Tuple.Create(" menuid=\"", 1822), Tuple.Create("\"", 1848)
            
            #line 58 "..\..\Views\Home\lefts.cshtml"
                                          , Tuple.Create(Tuple.Create("", 1831), Tuple.Create<System.Object, System.Int32>(subMenu.MenuID
            
            #line default
            #line hidden
, 1831), false)
);

WriteLiteral("><span><img");

WriteAttribute("src", Tuple.Create(" src=\"", 1860), Tuple.Create("\"", 1897)
, Tuple.Create(Tuple.Create("", 1866), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Home/img/leftico01.png")
, 1866), false)
);

WriteLiteral(" /></span>");

            
            #line 58 "..\..\Views\Home\lefts.cshtml"
                                                                                                                                                                                                  Write(subMenu.MenuName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <ul");

WriteLiteral(" class=\"menuson\"");

WriteLiteral(">\r\n");

            
            #line 60 "..\..\Views\Home\lefts.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\Home\lefts.cshtml"
                             if (subMenu.Children != null)
                            {
                                foreach (Menu subMenu2 in subMenu.Children)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteLiteral(" style=\"margin-left:-30px;\"");

WriteAttribute("url", Tuple.Create(" url=\"", 2250), Tuple.Create("\"", 2301)
            
            #line 64 "..\..\Views\Home\lefts.cshtml"
, Tuple.Create(Tuple.Create("", 2256), Tuple.Create<System.Object, System.Int32>(subMenu2.LinkUrl.Replace("Frame=1", "1=1")
            
            #line default
            #line hidden
, 2256), false)
);

WriteAttribute("menuid", Tuple.Create(" menuid=\"", 2302), Tuple.Create("\"", 2329)
            
            #line 64 "..\..\Views\Home\lefts.cshtml"
                                                , Tuple.Create(Tuple.Create("", 2311), Tuple.Create<System.Object, System.Int32>(subMenu2.MenuID
            
            #line default
            #line hidden
, 2311), false)
);

WriteLiteral(">\r\n                                        <cite></cite>\r\n                       " +
"                 <a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(">");

            
            #line 66 "..\..\Views\Home\lefts.cshtml"
                                                                  Write(subMenu2.MenuName);

            
            #line default
            #line hidden
WriteLiteral("</a><i></i>\r\n                                    </li>\r\n");

            
            #line 68 "..\..\Views\Home\lefts.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </dd>\r\n");

            
            #line 72 "..\..\Views\Home\lefts.cshtml"
                }
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </dl>\r\n\r\n</body>\r\n\r\n</html>\r\n\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2749), Tuple.Create("\"", 2786)
, Tuple.Create(Tuple.Create("", 2756), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Home/css/shcommon.css")
, 2756), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function () {
            
            jQuery("".menuson li"").click(function () {
                liclick(jQuery(this));
            });
            resizeWin();
            window.onresize = resizeWin;
            var firstli = jQuery('body').find("".location"")[0];
            if (jQuery(firstli).attr(""url"")) {
                liclick(firstli);
            }
            $("".menuson li:first"").addClass(""active"");

            liclick(jQuery("".menuson li:first""));
        });

        function liclick(obj) {
            parent.addTab(jQuery(obj).text().trim(), jQuery(obj).attr(""url""), jQuery(obj).attr(""menuId"") + ""_Frame"");
        }

        function resizeWin() {
            var bodyHeight = jQuery(window).height(); //浏览器当前窗口文档body的高度
            var bodyWidth = jQuery(window).width();
            jQuery("".leftmenu"").css(""height"", bodyHeight);
            jQuery("".leftmenu"").css(""height"", bodyHeight + 5);
        }

    </script>
");

        }
    }
}
#pragma warning restore 1591
