#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/log.cshtml")]
    public partial class _Views_Home_log_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_log_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\log.cshtml"
  
    ViewBag.Title = "log";
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n    <title>操作日志</title>\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Home\log.cshtml"
Write(RenderPage("~/Views/includeM/head.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Static/manage/js/checkfrom.js\"");

WriteLiteral("></script>\r\n</head>\r\n\r\n<body>\r\n\r\n    <div");

WriteLiteral(" class=\"place\"");

WriteLiteral(">\r\n        <span>位置：</span>\r\n        <ul");

WriteLiteral(" class=\"placeul\"");

WriteLiteral(">\r\n            <li><a");

WriteLiteral(" href=\"/Views/Manage/mains\"");

WriteLiteral(">首页</a></li>\r\n            <li>操作日志</li>\r\n        </ul>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"rightinfo\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" name=\"formlist\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(" action=\"news.php?action=del&pid=&ty=&tty=\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"tools\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n                    <li>&nbsp;<a");

WriteLiteral(" href=\"?action=alldel\"");

WriteLiteral(" onclick=\"return confirm(\'确定清空所有操作日志吗？\\n\\n清空后不能恢复！\');\"");

WriteLiteral(" class=\"Botton\"");

WriteLiteral("> 清空日志</a></li>\r\n                    <a");

WriteLiteral(" href=\"news.php?pid=&ty=&tty=&\"");

WriteLiteral("><img");

WriteLiteral(" src=\"/Static/Home/img/sx.jpg\"");

WriteLiteral(" /></a>\r\n                    <li>&nbsp;<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"all\"");

WriteLiteral(" onclick=\"CheckAll(this);\"");

WriteLiteral("> 全选</li>\r\n                    <input");

WriteLiteral(" type=\"image\"");

WriteLiteral(" src=\"/Static/Home/img/del.jpg\"");

WriteLiteral(" onclick=\"return checkData();\"");

WriteLiteral(" name=\"ok\"");

WriteLiteral(" value=\"删 除\"");

WriteLiteral(" />\r\n                </ul>\r\n\r\n            </div>\r\n\r\n\r\n            <table");

WriteLiteral(" class=\"tablelist\"");

WriteLiteral(">\r\n                <thead>\r\n                    <tr>\r\n                        <th" +
"");

WriteLiteral(" width=\"6%\"");

WriteLiteral(">选择</th>\r\n                        <th");

WriteLiteral(" width=\"7%\"");

WriteLiteral(">编号</th>\r\n                        <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(">用户名</th>\r\n                        <th");

WriteLiteral(" width=\"47%\"");

WriteLiteral(">操作内容</th>\r\n                        <th");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">IP</th>\r\n                        <th");

WriteLiteral(" width=\"13%\"");

WriteLiteral(">操作时间</th>\r\n                    </tr>\r\n                </thead>\r\n                " +
"<tbody>\r\n                    <tr>\r\n                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"370\"");

WriteLiteral(@"></td>
                        <td>370</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2017-02-10 12:31:16</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"369\"");

WriteLiteral(@"></td>
                        <td>369</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2017-02-10 12:18:52</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"368\"");

WriteLiteral(@"></td>
                        <td>368</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2017-02-10 11:45:22</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"367\"");

WriteLiteral(@"></td>
                        <td>367</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2017-02-10 11:34:47</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"366\"");

WriteLiteral(@"></td>
                        <td>366</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2017-02-10 10:28:54</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"365\"");

WriteLiteral(@"></td>
                        <td>365</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2017-02-10 10:25:53</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"364\"");

WriteLiteral(@"></td>
                        <td>364</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2017-02-10 10:25:11</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"363\"");

WriteLiteral(@"></td>
                        <td>363</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2017-02-10 10:24:57</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"362\"");

WriteLiteral(@"></td>
                        <td>362</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2016-12-28 15:43:56</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"361\"");

WriteLiteral(@"></td>
                        <td>361</td>
                        <td>admin</td>
                        <td>编辑广告信息</td>
                        <td>180.166.151.214</td>
                        <td>2016-12-23 13:29:36</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"360\"");

WriteLiteral(@"></td>
                        <td>360</td>
                        <td>admin</td>
                        <td>编辑广告信息</td>
                        <td>180.166.151.214</td>
                        <td>2016-12-23 13:29:22</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"359\"");

WriteLiteral(@"></td>
                        <td>359</td>
                        <td>admin</td>
                        <td>编辑广告信息</td>
                        <td>180.166.151.214</td>
                        <td>2016-12-23 13:29:09</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"358\"");

WriteLiteral(@"></td>
                        <td>358</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2016-12-23 13:28:51</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"357\"");

WriteLiteral(@"></td>
                        <td>357</td>
                        <td>admin</td>
                        <td>编辑单页面内容</td>
                        <td>180.166.151.214</td>
                        <td>2016-12-22 13:02:24</td>
                    </tr>
                    <tr>
                        <td><input");

WriteLiteral(" name=\"checkid[]\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"checkid[]\"");

WriteLiteral(" value=\"356\"");

WriteLiteral(@"></td>
                        <td>356</td>
                        <td>admin</td>
                        <td>登录管理后台</td>
                        <td>180.166.151.214</td>
                        <td>2016-12-22 13:01:33</td>
                    </tr>

                </tbody>
            </table>

            <div");

WriteLiteral(" class=\"fy\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"javascript:void()\"");

WriteLiteral(">首页</a>\r\n                <a");

WriteLiteral(" href=\"javascript:void()\"");

WriteLiteral(">上一页</a>\r\n                <a");

WriteLiteral(" href=\"javascript:void()\"");

WriteLiteral(" id=\"active1\"");

WriteLiteral(">1</a>\r\n                <a");

WriteLiteral(" href=\"?&page=2\"");

WriteLiteral(">2</a>\r\n                <a");

WriteLiteral(" href=\"?&page=3\"");

WriteLiteral(">3</a>\r\n                <a");

WriteLiteral(" href=\"?&page=4\"");

WriteLiteral(">4</a>\r\n                <a");

WriteLiteral(" href=\"?&page=5\"");

WriteLiteral(">5</a>\r\n                <a");

WriteLiteral(" href=\"?&page=6\"");

WriteLiteral(">6</a>\r\n                <a");

WriteLiteral(" href=\"?&page=7\"");

WriteLiteral(">7</a>\r\n                <a");

WriteLiteral(" href=\"?&page=8\"");

WriteLiteral(">8</a>\r\n                <a");

WriteLiteral(" href=\'?&page=2\'");

WriteLiteral(">下一页</a>\r\n                <a");

WriteLiteral(" href=\'?&page=25\'");

WriteLiteral(">末页</a>\r\n            </div>\r\n        </form>\r\n\r\n\r\n    </div>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\t$(\'.tablelist tbody tr:odd\').addClass(\'odd\');\r\n    </script>\r\n\r\n</body>\r\n\r\n</" +
"html>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
