#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Login.cshtml")]
    public partial class _Views_Home_Login_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Login.cshtml"
   
    ViewBag.Title = "登录界面";
   Layout = null;
   
   
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n\r\n<head>\r\n    <title>欢迎登录后台管理系统</title>\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\Home\Login.cshtml"
Write(RenderPage("~/Views/includeM/head.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Static/Home/js/cloud.js\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 389), Tuple.Create("\"", 420)
, Tuple.Create(Tuple.Create("", 395), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Home/js/Login.js")
, 395), false)
);

WriteLiteral("></script>\r\n   \r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
            jQuery(function () {
                jQuery('.loginbox').css({
                    'position': 'absolute',
                    'left': (jQuery(window).width() - 692) / 2
                });

                jQuery(window).resize(function () {
                    jQuery('.loginbox').css({
                        'position': 'absolute',
                        'left': (jQuery(window).width() - 692) / 2
                    });
                });

                var viewModel = new loginViewModel();
                viewModel.init();
            });
        </script>

</head>
<body");

WriteLiteral(" style=\"background-color:#1c77ac; background-image:url(/Static/Home/img/light.png" +
"); background-repeat:no-repeat; background-position:center top; overflow:hidden;" +
"\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"mainBody\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"cloud1\"");

WriteLiteral(" class=\"cloud\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" id=\"cloud2\"");

WriteLiteral(" class=\"cloud\"");

WriteLiteral("></div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"logintop\"");

WriteLiteral(">\r\n        <span>欢迎登录后台管理界面平台</span>\r\n        <ul>\r\n            <li>\r\n           " +
"     <a");

WriteLiteral(" href=\"./\"");

WriteLiteral(">回首页</a>\r\n            </li>\r\n            <li>\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">帮助</a>\r\n            </li>\r\n            <li>\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">关于</a>\r\n            </li>\r\n        </ul>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"loginbody\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"systemlogo\"");

WriteLiteral("></span>\r\n        <div");

WriteLiteral(" class=\"loginbox\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li><input");

WriteLiteral(" name=\"txtName\"");

WriteLiteral(" id=\"txtName\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"loginuser\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" /></li>\r\n                    <li><input");

WriteLiteral(" name=\"txtPwd\"");

WriteLiteral(" id=\"txtPwd\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"loginpwd\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" /></li>\r\n                    <li><input");

WriteLiteral(" name=\"btn_login\"");

WriteLiteral(" id=\"btn_login\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"loginbtn\"");

WriteLiteral(" value=\"登录\"");

WriteLiteral(" /></li>\r\n                </ul>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"loginbm\"");

WriteLiteral("></div>\r\n</body>\r\n\r\n</html>");

        }
    }
}
#pragma warning restore 1591
