#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/news_cat.cshtml")]
    public partial class _Views_Home_news_cat_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_news_cat_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\news_cat.cshtml"
  
    ViewBag.Title = "news_cat";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n    <title>s栏目管理</title>\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Home\news_cat.cshtml"
Write(RenderPage("~/Views/includeM/head.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Static/manage/js/checkfrom.js\"");

WriteLiteral("></script>\r\n</head>\r\n\r\n<body>\r\n    <div");

WriteLiteral(" class=\"place\"");

WriteLiteral(">\r\n        <span>位置：</span>\r\n        <ul");

WriteLiteral(" class=\"placeul\"");

WriteLiteral(">\r\n            <li><a");

WriteLiteral(" href=\"/Views/Manage/mains\"");

WriteLiteral(">首页</a></li>\r\n            <li>栏目管理</li>\r\n        </ul>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"rightinfo\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"tools\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"toolbar2\"");

WriteLiteral(">\r\n                <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"current\"");

WriteLiteral(">管理栏目</a></li>\r\n            </ul>\r\n        </div>\r\n\r\n        <div>\r\n            <" +
"table");

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" class=\"cast_list\"");

WriteLiteral(">\r\n                <tr>\r\n                    <th");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">栏目ID</th>\r\n                    <th");

WriteLiteral(" width=\"31%\"");

WriteLiteral(">栏目名称</th>\r\n                    <th");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">栏目类型</th>\r\n                    <th");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">数据量</th>\r\n                    <th");

WriteLiteral(" width=\"32%\"");

WriteLiteral(">管理操作</th>\r\n                </tr>\r\n\r\n                <tr>\r\n                    <t" +
"d");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">64</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">【典型案例】</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">15</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("> </td>\r\n                </tr>\r\n                <tr>\r\n                    <td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">65</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├综合布线系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=65\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=65&id=65\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">69</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└地铁自动化系统集成方案</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=69\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=65&tty=69&id=69\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">71</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└智能小区解决方案</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=71\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=65&tty=71&id=71\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">72</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└校园一卡通解决方案</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=72\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=65&tty=72&id=72\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">73</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└医疗行业智能化解决方案</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=73\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=65&tty=73&id=73\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">66</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├智能化停车场系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=66\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=66&id=66\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">70</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└车位引导系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=70\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=66&tty=70&id=70\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">74</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└区位引导系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=74\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=66&tty=74&id=74\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">75</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└综合车辆引导系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=75\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=66&tty=75&id=75\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">76</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└停车场综合智能化</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=76\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=66&tty=76&id=76\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">67</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├通信网络系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=67\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=67&id=67\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">77</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└网络工程</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=77\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=67&tty=77&id=77\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">78</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└数据中心</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=78\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=67&tty=78&id=78\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">79</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└容灾</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=79\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=67&tty=79&id=79\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">80</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└安全服务</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=80\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=67&tty=80&id=80\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">68</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├安全防范系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">3</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=68\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=68&id=68\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">81</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└数字视频安防监控</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">3</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=81\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=68&tty=81&id=81\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">82</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└模拟视频安防监控</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">3</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=82\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=68&tty=82&id=82\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">83</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└周界防范、电子巡更系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">3</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=83\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=64&ty=68&tty=83&id=83\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">1</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">【关于珺意】</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">5</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("> </td>\r\n                </tr>\r\n                <tr>\r\n                    <td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">7</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├公司介绍</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">1</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=7\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=1&ty=7&id=7\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">10</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├资质荣誉</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">1</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=10\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=1&ty=10&id=10\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├人才招聘</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">招聘模块</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">1</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=11\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=1&ty=11&id=11\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">12</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├联系我们</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">1</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=12\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=1&ty=12&id=12\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">2</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">【自主产品】</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">0</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("> </td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    <td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">3</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">【解决方案】</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">29</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("> </td>\r\n                </tr>\r\n                <tr>\r\n                    <td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">59</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├智能化系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">新闻列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=59\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&id=59\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">13</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└考勤系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=13\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&tty=13&id=13\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">14</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└门禁系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=14\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&tty=14&id=14\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">15</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└就餐系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=15\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&tty=15&id=15\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">20</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└水控系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=20\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&tty=20&id=20\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">21</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└电控系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=21\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&tty=21&id=21\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">23</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└巡更系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=23\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&tty=23&id=23\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">26</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└访客系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=26\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&tty=26&id=26\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">29</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└班车系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=29\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&tty=29&id=29\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">32</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└梯控系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=32\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=59&tty=32&id=32\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">60</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├行业软件</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">新闻列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=60\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&id=60\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">16</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└出入管理</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=16\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&tty=16&id=16\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">19</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└场馆消费</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=19\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&tty=19&id=19\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">22</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└会议签到</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=22\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&tty=22&id=22\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">24</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└自助洗衣</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=24\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&tty=24&id=24\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">25</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└宿舍管理</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=25\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&tty=25&id=25\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">27</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└停车管理</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=27\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&tty=27&id=27\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">28</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└人力资源</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=28\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&tty=28&id=28\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">30</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└自动售货</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=30\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&tty=30&id=30\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">33</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└证卡制作</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">9</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=33\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=60&tty=33&id=33\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">63</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├解决方案</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">新闻列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=63\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&id=63\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">34</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└视频监控</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=34\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=34&id=34\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">35</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└防盗报警</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=35\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=35&id=35\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">36</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└电子围栏</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=36\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=36&id=36\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">37</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└综合布线</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=37\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=37&id=37\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">38</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└楼宇自控</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=38\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=38&id=38\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">40</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└无线网络</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=40\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=40&id=40\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">41</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└集中抄表</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=41\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=41&id=41\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">42</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└照明系统</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=42\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=42&id=42\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">43</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└机房工程</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=43\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=43&id=43\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">44</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└智能家居</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=44\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=44&id=44\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">45</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└公共广播</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=45\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=45&id=45\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">46</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;&nbsp;└└视频会议</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">11</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=46\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=3&ty=63&tty=46&id=46\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall1();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">4</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">【成功案例】</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">12</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("> </td>\r\n                </tr>\r\n                <tr>\r\n                    <td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">47</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├政府机关</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">2</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=47\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=4&ty=47&id=47\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">48</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├医疗卫生</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">1</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=48\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=4&ty=48&id=48\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">49</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├外资企业</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">2</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=49\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=4&ty=49&id=49\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">50</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├国有企业</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">5</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=50\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=4&ty=50&id=50\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">51</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├教育行业</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">图片列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">2</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=51\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=4&ty=51&id=51\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n\r\n                <tr>\r\n                  " +
"  <td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">5</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">【新闻中心】</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">新闻列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">5</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("> </td>\r\n                </tr>\r\n                <tr>\r\n                    <td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">52</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├行业动态</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">新闻列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">3</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=52\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=5&ty=52&id=52\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">53</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">&nbsp;├公司新闻</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">新闻列表</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">2</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("><a");

WriteLiteral(" href=\"news_cat_edit.php?id=53\"");

WriteLiteral(">修改</a>&nbsp;|&nbsp;<a");

WriteLiteral(" href=\"?action=del&pid=5&ty=53&id=53\"");

WriteLiteral(" onclick=\"return ConfirmDelSmall();\"");

WriteLiteral(">删除</a></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    " +
"<td");

WriteLiteral(" width=\"11%\"");

WriteLiteral(">57</td>\r\n                    <td");

WriteLiteral(" width=\"31%\"");

WriteLiteral(" align=\"left\"");

WriteLiteral(" class=\"tl\"");

WriteLiteral(">【智慧珺意】</td>\r\n                    <td");

WriteLiteral(" width=\"14%\"");

WriteLiteral(">单一内容</td>\r\n                    <td");

WriteLiteral(" width=\"12%\"");

WriteLiteral(">0</td>\r\n                    <td");

WriteLiteral(" width=\"32%\"");

WriteLiteral("> </td>\r\n                </tr>\r\n            </table>\r\n        </div>\r\n        <di" +
"v");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n</body>\r\n\r\n</html>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
