#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.PortalIPS;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PortalIPS/Views/VoteResult/_/Create.cshtml")]
    public partial class _Areas_PortalIPS_Views_VoteResult___Create_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_PortalIPS_Views_VoteResult___Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="新建投票结果";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/PortalIPS/VoteResult/Create\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_VoteResultID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_VoteResultID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">结果编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"VoteResultID\"");

WriteLiteral(" name=\"VoteResultID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 872), Tuple.Create("\"", 901)
            
            #line 21 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 880), Tuple.Create<System.Object, System.Int32>(Model.VoteResultID
            
            #line default
            #line hidden
, 880), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_VoteID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_VoteID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">所属投票主题：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"VoteID\"");

WriteLiteral(" name=\"VoteID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1137), Tuple.Create("\"", 1160)
            
            #line 24 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1145), Tuple.Create<System.Object, System.Int32>(Model.VoteID
            
            #line default
            #line hidden
, 1145), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_VoteItemID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_VoteItemID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">VoteItemID：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"VoteItemID\"");

WriteLiteral(" name=\"VoteItemID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1401), Tuple.Create("\"", 1428)
            
            #line 27 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1409), Tuple.Create<System.Object, System.Int32>(Model.VoteItemID
            
            #line default
            #line hidden
, 1409), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_VoteItem\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_VoteItem\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">投票项：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"VoteItem\"");

WriteLiteral(" name=\"VoteItem\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1653), Tuple.Create("\"", 1678)
            
            #line 30 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1661), Tuple.Create<System.Object, System.Int32>(Model.VoteItem
            
            #line default
            #line hidden
, 1661), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_UserID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_UserID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">投票会员编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"UserID\"");

WriteLiteral(" name=\"UserID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1899), Tuple.Create("\"", 1922)
            
            #line 33 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1907), Tuple.Create<System.Object, System.Int32>(Model.UserID
            
            #line default
            #line hidden
, 1907), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IP\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IP\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">投票IP：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"IP\"");

WriteLiteral(" name=\"IP\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2124), Tuple.Create("\"", 2143)
            
            #line 36 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2132), Tuple.Create<System.Object, System.Int32>(Model.IP
            
            #line default
            #line hidden
, 2132), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_VoteTime\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_VoteTime\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">投票时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"VoteTime\"");

WriteLiteral(" name=\"VoteTime\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2370), Tuple.Create("\"", 2395)
            
            #line 39 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2378), Tuple.Create<System.Object, System.Int32>(Model.VoteTime
            
            #line default
            #line hidden
, 2378), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_CookieKey\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_CookieKey\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">Cookie：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CookieKey\"");

WriteLiteral(" name=\"CookieKey\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2627), Tuple.Create("\"", 2653)
            
            #line 42 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2635), Tuple.Create<System.Object, System.Int32>(Model.CookieKey
            
            #line default
            #line hidden
, 2635), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 47 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
   Write(RenderPage("~/Areas/PortalIPS/Views/VoteResult/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
function CheckConditions(){
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 75 "..\..\Areas\PortalIPS\Views\VoteResult\_\Create.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/VoteResult/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
