
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的方法，请在此文件的上级目录中的CategoryTypeDAL重写(override)该方法。
//     如有问题联系zongeasy@qq.com
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.ComponentModel;
using Yamon.Framework.DBUtility;
using System.Collections;
using Yamon.Framework.Common.DataBase;
using Yamon.Framework.Common;
using Yamon.Framework.Common.IO;
using System.IO;
using System.Linq.Expressions;
using Yamon.Framework.DAL;
using Yamon.Module.PortalIPS.Entity;

namespace Yamon.Module.PortalIPS.DAL
{
    /// <summary>
    /// 栏目类型模型实体类
    ///</summary>
    public partial class _CategoryTypeDAL : BaseModelDAL<CategoryType>
    {
        public _CategoryTypeDAL():base("UCenter")
        {
        }

		/// <summary>
        /// 是否启用（Flag）字段的数据集合（键值对）
        /// </summary>
		public MyNameValueCollection NameValue_Flag
		{
			get
			{
			    MyNameValueCollection nv=new MyNameValueCollection();
                nv.Add("1", "是");
                nv.Add("0", "否");
                return nv;

			}
		}




		/// <summary>
		/// 获取分页的数据实体列表
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>实体列表</returns>
		public virtual List<CategoryType> GetEntityListByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="TypeName,DisplayName,Description,Flag";
			return GetEntityListByPage("1=1 "+ where, searchParams,order,fields, rows,page,topN,out totalRows);
		}

		/// <summary>
		/// 获取分页的数据列表DataTable
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>DataTable</returns>
		public virtual DataTable GetEntityTableByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="TypeName,DisplayName,Description,Flag";
			return GetEntityTableByPage("1=1 "+ where, searchParams,order,fields,rows,page,topN,out totalRows);
		}

		/// <summary>
        /// 拼接查询Sql语句及参数
        /// </summary>
        /// <param name="nv">页面传递的参数集合</param>
        /// <param name="notIn">排除字段</param>
        /// <param name="arrParam">out查询参数</param>
        /// <returns>查询Sql语句</returns>
		public virtual string GetSearchSql(string notIn,out object[] arrParam)
		{
			StringBuilder sb=new StringBuilder();
			string value="";
			string value1 = "";
			string value2 = "";
			ArrayList param=new ArrayList();
			arrParam=param.ToArray();
			return sb.ToString();

		}

		
	    public virtual CategoryType GetModelValue(CategoryType model)
        {
            return model;
        }
		/// <summary>
        /// 设置栏目类型模型实体(CategoryType)的显示值
        /// </summary>
        /// <param name="model">栏目类型模型实体(CategoryType)</param>
        /// <returns>栏目类型模型实体(CategoryType)</returns>
		public virtual CategoryType GetModelShowValue(CategoryType model,bool clearValue=false)
        {
            model=GetModelValue(model);
			if (model.Flag!=null)
			{
				model.Flag_ShowValue=NameValue_Flag.Get(model.Flag.ToString());
			}
			if(clearValue)
			{
				model.Flag = null;
			}
			return model;
		}
		
		/// <summary>
        /// 设置栏目类型模型实体(CategoryType)的列表显示值
        /// </summary>
        /// <param name="model">栏目类型模型实体(CategoryType)</param>
        /// <returns>栏目类型模型实体(CategoryType)</returns>
		public virtual CategoryType GetModelGridShowValue(CategoryType model){
			model=GetModelShowValue(model);
			return model;
        }

        public virtual CategoryType GetInfoByID(object id){
            CategoryType model = GetModelByID(id);
            model = GetModelShowValue(model);
            return model;
        } 


      #region 新建相关方法
		/// <summary>
        /// 设置新增入库时栏目类型模型实体(CategoryType)默认值
        /// </summary>
        /// <param name="model">栏目类型模型实体(CategoryType)</param>
        /// <returns>栏目类型模型实体(CategoryType)</returns>
		public virtual CategoryType GetInsertModelValue(CategoryType model)
		{
			return model;
		}		/// <summary>
        /// 设置新建页面的栏目类型模型实体(CategoryType)默认值
        /// </summary>
        /// <param name="model">栏目类型模型实体(CategoryType)</param>
        /// <returns>栏目类型模型实体(CategoryType)</returns>
		public virtual CategoryType GetCreateFormDefaultValue()
		{
            CategoryType model = new CategoryType();
            return model;
		}

		/// <summary>
        /// 新建数据格式验证
        /// </summary>
        /// <param name="model">栏目类型模型实体(CategoryType)</param>
        public virtual void CreateFormValidator(CategoryType model)
        {
			string value="";
			
			//TypeName验证
			value = model.TypeName!=null ? model.TypeName.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("编码名称不能为空！");
		            }
			
			//DisplayName验证
			value = model.DisplayName!=null ? model.DisplayName.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("名称不能为空！");
		            }
			
			//Flag验证
			value = model.Flag!=null ? model.Flag.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("是否启用不能为空！");
		            }
}
      #endregion

      #region 修改相关方法
		/// <summary>
        /// 设置更新入库时栏目类型模型实体(CategoryType)默认值
        /// </summary>
        /// <param name="model">栏目类型模型实体(CategoryType)</param>
        /// <returns>栏目类型模型实体(CategoryType)</returns>
		public virtual CategoryType GetUpdateModelValue(CategoryType model)
		{
			return model;
		}		/// <summary>
        /// 设置编辑页面的栏目类型模型实体(CategoryType)默认值
        /// </summary>
        /// <param name="model">栏目类型模型实体(CategoryType)</param>
        /// <returns>栏目类型模型实体(CategoryType)</returns>
		public virtual CategoryType GetEditFormDefaultValue(CategoryType model)
		{
			return model;
		}

		/// <summary>
        /// 编辑数据格式验证
        /// </summary>
        /// <param name="model">栏目类型模型实体(CategoryType)</param>
        public virtual void EditFormValidator(CategoryType model)
        {
			string value="";
			
			//TypeName验证
			value = model.TypeName!=null ? model.TypeName.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("编码名称不能为空！");
		            }
			
			//DisplayName验证
			value = model.DisplayName!=null ? model.DisplayName.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("名称不能为空！");
		            }
			
			//Flag验证
			value = model.Flag!=null ? model.Flag.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("是否启用不能为空！");
		            }
}
      #endregion

    }
}
