
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的方法，请在此文件的上级目录中的VoteDAL重写(override)该方法。
//     如有问题联系zongeasy@qq.com
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.ComponentModel;
using Yamon.Framework.DBUtility;
using System.Collections;
using Yamon.Framework.Common.DataBase;
using Yamon.Framework.Common;
using Yamon.Framework.Common.IO;
using System.IO;
using System.Linq.Expressions;
using Yamon.Framework.DAL;
using Yamon.Module.PortalIPS.Entity;

namespace Yamon.Module.PortalIPS.DAL
{
    /// <summary>
    /// 投票模型实体类
    ///</summary>
    public partial class _VoteDAL : BaseModelDAL<Vote>
    {
        public _VoteDAL():base("UCenter")
        {
        }

		/// <summary>
        /// 状态（Status）字段的数据集合（键值对）
        /// </summary>
		public MyNameValueCollection NameValue_Status
		{
			get
			{
			    MyNameValueCollection nv=new MyNameValueCollection();
                nv.Add("1", "启用");
                nv.Add("0", "停用");
                return nv;

			}
		}



		/// <summary>
		/// 获取数据实体列表(栏目过滤)
		///</summary>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="fields">查询的字段</param>
		/// <returns>实体列表</returns>
        public virtual List<Vote> GetEntityList_CategoryID(int topN = 0,string fields="")
        {
            object[] arrParams = new object[] { RequestHelper.GetString("CategoryID") };
            return GetEntityList("1=1 AND CategoryID=? ",arrParams, "", topN,fields);
        }
		
		/// <summary>
		/// 获取数据实体列表(栏目过滤)
		///</summary>
		/// <param name="fields">查询的字段</param>
		/// <returns>实体列表</returns>
        public virtual List<Vote> GetAllEntityList_CategoryID(string fields="")
        {
            return GetEntityList_CategoryID(0,fields);
        }
		
		/// <summary>
		/// 获取分页的数据实体列表(栏目过滤)
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>实体列表</returns>
        public virtual List<Vote> GetEntityListByPage_CategoryID(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
        {
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
			   order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			object[] arrParams = new object[] { RequestHelper.GetString("CategoryID") };
            arrParams=arrParams.Concat(searchParams).ToArray();
            string fields="VoteID,VoteName,Status,VoteContent,VoteCount";
            return GetEntityListByPage("1=1 AND CategoryID=? "+ where, arrParams,order,fields ,rows,page,topN,out totalRows);
        }
		
		/// <summary>
		/// 获取数据列表DataTable(栏目过滤)
		///</summary>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="fields">查询的字段</param>
		/// <returns>数据列表</returns>
        public virtual DataTable GetEntityTable_CategoryID(int topN = 0,string fields="")
        {
            object[] arrParams = new object[] { RequestHelper.GetString("CategoryID") };
            return GetEntityTable("1=1 AND CategoryID=? ",arrParams, "", topN,fields);
        }
		
		/// <summary>
		/// 获取数据列表DataTable(栏目过滤)
		///</summary>
		/// <param name="fields">查询的字段</param>
		/// <returns>数据列表</returns>
        public virtual DataTable GetAllEntityTable_CategoryID(string fields="")
        {
        	return GetEntityTable_CategoryID(0,fields);
        }
		/// <summary>
		/// 获取分页的数据列表DataTable(栏目过滤)
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>DataTable</returns>
        public virtual DataTable GetEntityTableByPage_CategoryID(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
        {
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
			    order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			object[] arrParams = new object[] { RequestHelper.GetString("CategoryID") };
            arrParams=arrParams.Concat(searchParams).ToArray();
            string fields="VoteID,VoteName,Status,VoteContent,VoteCount";
            return GetEntityTableByPage("1=1 AND CategoryID=? "+ where, arrParams,order,fields, rows,page,topN,out totalRows);
        }

		/// <summary>
		/// 获取分页的数据实体列表
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>实体列表</returns>
		public virtual List<Vote> GetEntityListByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="VoteID,VoteName,Status,VoteContent,VoteCount";
			return GetEntityListByPage("1=1 "+ where, searchParams,order,fields, rows,page,topN,out totalRows);
		}

		/// <summary>
		/// 获取分页的数据列表DataTable
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>DataTable</returns>
		public virtual DataTable GetEntityTableByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="VoteID,VoteName,Status,VoteContent,VoteCount";
			return GetEntityTableByPage("1=1 "+ where, searchParams,order,fields,rows,page,topN,out totalRows);
		}

		/// <summary>
        /// 拼接查询Sql语句及参数
        /// </summary>
        /// <param name="nv">页面传递的参数集合</param>
        /// <param name="notIn">排除字段</param>
        /// <param name="arrParam">out查询参数</param>
        /// <returns>查询Sql语句</returns>
		public virtual string GetSearchSql(string notIn,out object[] arrParam)
		{
			StringBuilder sb=new StringBuilder();
			string value="";
			string value1 = "";
			string value2 = "";
			ArrayList param=new ArrayList();
			arrParam=param.ToArray();
			return sb.ToString();

		}

		
	    public virtual Vote GetModelValue(Vote model)
        {
            return model;
        }
		/// <summary>
        /// 设置投票模型实体(Vote)的显示值
        /// </summary>
        /// <param name="model">投票模型实体(Vote)</param>
        /// <returns>投票模型实体(Vote)</returns>
		public virtual Vote GetModelShowValue(Vote model,bool clearValue=false)
        {
            model=GetModelValue(model);
			if (model.Status!=null)
			{
				model.Status_ShowValue=NameValue_Status.Get(model.Status.ToString());
			}
			if(clearValue)
			{
				model.Status = null;
			}
			return model;
		}
		
		/// <summary>
        /// 设置投票模型实体(Vote)的列表显示值
        /// </summary>
        /// <param name="model">投票模型实体(Vote)</param>
        /// <returns>投票模型实体(Vote)</returns>
		public virtual Vote GetModelGridShowValue(Vote model){
			model=GetModelShowValue(model);
			return model;
        }

        public virtual Vote GetInfoByID(object id){
            Vote model = GetModelByID(id);
            model = GetModelShowValue(model);
            return model;
        } 


      #region 新建相关方法
		/// <summary>
        /// 设置新增入库时投票模型实体(Vote)默认值
        /// </summary>
        /// <param name="model">投票模型实体(Vote)</param>
        /// <returns>投票模型实体(Vote)</returns>
		public virtual Vote GetInsertModelValue(Vote model)
		{
			model.VoteID =(Guid.NewGuid().ToString());
			model.CategoryID =(RequestHelper.GetString("CategoryID"));
			model.AppID =(CookieHelper.GetCookie("CityID"));
			model.StartTime =DateTime.Now;
			model.EndTime =DateTime.Now;
			model.VoteCount =0;
			model.MaxSelectNum =1;
			return model;
		}		/// <summary>
        /// 设置新建页面的投票模型实体(Vote)默认值
        /// </summary>
        /// <param name="model">投票模型实体(Vote)</param>
        /// <returns>投票模型实体(Vote)</returns>
		public virtual Vote GetCreateFormDefaultValue()
		{
            Vote model = new Vote();
			model.VoteID=(Guid.NewGuid().ToString());
			model.CategoryID=(RequestHelper.GetString("CategoryID"));
			model.AppID=(CookieHelper.GetCookie("CityID"));
			model.Status=1;
            return model;
		}

		/// <summary>
        /// 新建数据格式验证
        /// </summary>
        /// <param name="model">投票模型实体(Vote)</param>
        public virtual void CreateFormValidator(Vote model)
        {
			string value="";
			
			//VoteID验证
			value = model.VoteID!=null ? model.VoteID.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("ID不能为空！");
		            }
			
			//CategoryID验证
			value = model.CategoryID!=null ? model.CategoryID.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("所属栏目不能为空！");
		            }
			
			//VoteName验证
			value = model.VoteName!=null ? model.VoteName.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("投票主题不能为空！");
		            }
			
			//VoteItem验证
			value = model.VoteItem!=null ? model.VoteItem.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("投票选项不能为空！");
		            }
}
      #endregion

      #region 修改相关方法
		/// <summary>
        /// 设置更新入库时投票模型实体(Vote)默认值
        /// </summary>
        /// <param name="model">投票模型实体(Vote)</param>
        /// <returns>投票模型实体(Vote)</returns>
		public virtual Vote GetUpdateModelValue(Vote model)
		{
			model.CategoryID =null;
			model.AppID =null;
			model.VoteCount =null;
			return model;
		}		/// <summary>
        /// 设置编辑页面的投票模型实体(Vote)默认值
        /// </summary>
        /// <param name="model">投票模型实体(Vote)</param>
        /// <returns>投票模型实体(Vote)</returns>
		public virtual Vote GetEditFormDefaultValue(Vote model)
		{
			return model;
		}

		/// <summary>
        /// 编辑数据格式验证
        /// </summary>
        /// <param name="model">投票模型实体(Vote)</param>
        public virtual void EditFormValidator(Vote model)
        {
			string value="";
			
			//VoteName验证
			value = model.VoteName!=null ? model.VoteName.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("投票主题不能为空！");
		            }
			
			//VoteItem验证
			value = model.VoteItem!=null ? model.VoteItem.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("投票选项不能为空！");
		            }
}
      #endregion

    }
}
