
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的方法，请在此文件的上级目录中的VoteItemDAL重写(override)该方法。
//     如有问题联系zongeasy@qq.com
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.ComponentModel;
using Yamon.Framework.DBUtility;
using System.Collections;
using Yamon.Framework.Common.DataBase;
using Yamon.Framework.Common;
using Yamon.Framework.Common.IO;
using System.IO;
using System.Linq.Expressions;
using Yamon.Framework.DAL;
using Yamon.Module.PortalIPS.Entity;

namespace Yamon.Module.PortalIPS.DAL
{
    /// <summary>
    /// 投票选项模型实体类
    ///</summary>
    public partial class _VoteItemDAL : BaseModelDAL<VoteItem>
    {
        public _VoteItemDAL():base("UCenter")
        {
        }




		/// <summary>
		/// 获取数据实体列表(投票选项)
		///</summary>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="fields">查询的字段</param>
		/// <returns>实体列表</returns>
        public virtual List<VoteItem> GetEntityList_VoteID(int topN = 0,string fields="")
        {
            object[] arrParams = new object[] { RequestHelper.GetString("VoteID") };
            return GetEntityList("1=1 AND VoteID=? ",arrParams, "", topN,fields);
        }
		
		/// <summary>
		/// 获取数据实体列表(投票选项)
		///</summary>
		/// <param name="fields">查询的字段</param>
		/// <returns>实体列表</returns>
        public virtual List<VoteItem> GetAllEntityList_VoteID(string fields="")
        {
            return GetEntityList_VoteID(0,fields);
        }
		
		/// <summary>
		/// 获取分页的数据实体列表(投票选项)
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>实体列表</returns>
        public virtual List<VoteItem> GetEntityListByPage_VoteID(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
        {
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
			   order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			object[] arrParams = new object[] { RequestHelper.GetString("VoteID") };
            arrParams=arrParams.Concat(searchParams).ToArray();
            string fields="VoteItemID,ItemName,Weight,VoteCount";
            return GetEntityListByPage("1=1 AND VoteID=? "+ where, arrParams,order,fields ,rows,page,topN,out totalRows);
        }
		
		/// <summary>
		/// 获取数据列表DataTable(投票选项)
		///</summary>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="fields">查询的字段</param>
		/// <returns>数据列表</returns>
        public virtual DataTable GetEntityTable_VoteID(int topN = 0,string fields="")
        {
            object[] arrParams = new object[] { RequestHelper.GetString("VoteID") };
            return GetEntityTable("1=1 AND VoteID=? ",arrParams, "", topN,fields);
        }
		
		/// <summary>
		/// 获取数据列表DataTable(投票选项)
		///</summary>
		/// <param name="fields">查询的字段</param>
		/// <returns>数据列表</returns>
        public virtual DataTable GetAllEntityTable_VoteID(string fields="")
        {
        	return GetEntityTable_VoteID(0,fields);
        }
		/// <summary>
		/// 获取分页的数据列表DataTable(投票选项)
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>DataTable</returns>
        public virtual DataTable GetEntityTableByPage_VoteID(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
        {
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
			    order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			object[] arrParams = new object[] { RequestHelper.GetString("VoteID") };
            arrParams=arrParams.Concat(searchParams).ToArray();
            string fields="VoteItemID,ItemName,Weight,VoteCount";
            return GetEntityTableByPage("1=1 AND VoteID=? "+ where, arrParams,order,fields, rows,page,topN,out totalRows);
        }

		/// <summary>
		/// 获取分页的数据实体列表
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>实体列表</returns>
		public virtual List<VoteItem> GetEntityListByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="VoteItemID,ItemName,Weight,VoteCount";
			return GetEntityListByPage("1=1 "+ where, searchParams,order,fields, rows,page,topN,out totalRows);
		}

		/// <summary>
		/// 获取分页的数据列表DataTable
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>DataTable</returns>
		public virtual DataTable GetEntityTableByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="VoteItemID,ItemName,Weight,VoteCount";
			return GetEntityTableByPage("1=1 "+ where, searchParams,order,fields,rows,page,topN,out totalRows);
		}

		/// <summary>
        /// 拼接查询Sql语句及参数
        /// </summary>
        /// <param name="nv">页面传递的参数集合</param>
        /// <param name="notIn">排除字段</param>
        /// <param name="arrParam">out查询参数</param>
        /// <returns>查询Sql语句</returns>
		public virtual string GetSearchSql(string notIn,out object[] arrParam)
		{
			StringBuilder sb=new StringBuilder();
			string value="";
			string value1 = "";
			string value2 = "";
			ArrayList param=new ArrayList();
			arrParam=param.ToArray();
			return sb.ToString();

		}

		
	    public virtual VoteItem GetModelValue(VoteItem model)
        {
            return model;
        }
		/// <summary>
        /// 设置投票选项模型实体(VoteItem)的显示值
        /// </summary>
        /// <param name="model">投票选项模型实体(VoteItem)</param>
        /// <returns>投票选项模型实体(VoteItem)</returns>
		public virtual VoteItem GetModelShowValue(VoteItem model,bool clearValue=false)
        {
            model=GetModelValue(model);
			if(clearValue)
			{
			}
			return model;
		}
		
		/// <summary>
        /// 设置投票选项模型实体(VoteItem)的列表显示值
        /// </summary>
        /// <param name="model">投票选项模型实体(VoteItem)</param>
        /// <returns>投票选项模型实体(VoteItem)</returns>
		public virtual VoteItem GetModelGridShowValue(VoteItem model){
			model=GetModelShowValue(model);
			return model;
        }

        public virtual VoteItem GetInfoByID(object id){
            VoteItem model = GetModelByID(id);
            model = GetModelShowValue(model);
            return model;
        } 


      #region 新建相关方法
		/// <summary>
        /// 设置新增入库时投票选项模型实体(VoteItem)默认值
        /// </summary>
        /// <param name="model">投票选项模型实体(VoteItem)</param>
        /// <returns>投票选项模型实体(VoteItem)</returns>
		public virtual VoteItem GetInsertModelValue(VoteItem model)
		{
			model.VoteItemID =null;
			return model;
		}		/// <summary>
        /// 设置新建页面的投票选项模型实体(VoteItem)默认值
        /// </summary>
        /// <param name="model">投票选项模型实体(VoteItem)</param>
        /// <returns>投票选项模型实体(VoteItem)</returns>
		public virtual VoteItem GetCreateFormDefaultValue()
		{
            VoteItem model = new VoteItem();
            return model;
		}

		/// <summary>
        /// 新建数据格式验证
        /// </summary>
        /// <param name="model">投票选项模型实体(VoteItem)</param>
        public virtual void CreateFormValidator(VoteItem model)
        {
			string value="";
}
      #endregion

      #region 修改相关方法
		/// <summary>
        /// 设置更新入库时投票选项模型实体(VoteItem)默认值
        /// </summary>
        /// <param name="model">投票选项模型实体(VoteItem)</param>
        /// <returns>投票选项模型实体(VoteItem)</returns>
		public virtual VoteItem GetUpdateModelValue(VoteItem model)
		{
			model.VoteID =null;
			return model;
		}		/// <summary>
        /// 设置编辑页面的投票选项模型实体(VoteItem)默认值
        /// </summary>
        /// <param name="model">投票选项模型实体(VoteItem)</param>
        /// <returns>投票选项模型实体(VoteItem)</returns>
		public virtual VoteItem GetEditFormDefaultValue(VoteItem model)
		{
			return model;
		}

		/// <summary>
        /// 编辑数据格式验证
        /// </summary>
        /// <param name="model">投票选项模型实体(VoteItem)</param>
        public virtual void EditFormValidator(VoteItem model)
        {
			string value="";
}
      #endregion

    }
}
