#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.PortalIPS;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PortalIPS/Views/Advertisement/_/Show.cshtml")]
    public partial class _Areas_PortalIPS_Views_Advertisement___Show_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_PortalIPS_Views_Advertisement___Show_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #F6F6F6; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/PortalIPS/Advertisement/Show\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_ID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">ID：</td><td>&nbsp;<span");

WriteLiteral(" id=\"ID\"");

WriteLiteral(">");

            
            #line 18 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                    Write(Html.Raw(Model.ID));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Name\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Name\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">名称：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Name\"");

WriteLiteral(">");

            
            #line 19 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                          Write(Html.Raw(Model.Name));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Type\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Type\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">类型：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Type\"");

WriteLiteral(">");

            
            #line 20 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                          Write(Html.Raw(Model.Type_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Status\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Status\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">状态：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Status\"");

WriteLiteral(">");

            
            #line 21 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                                Write(Html.Raw(Model.Status_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Link\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Link\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">链接地址：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Link\"");

WriteLiteral(">");

            
            #line 22 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                            Write(Html.Raw(Model.Link));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Url\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Url\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">图片：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Url\"");

WriteLiteral(">");

            
            #line 23 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                       Write(Html.Raw(Model.Url));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Count\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Count\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">内容：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Count\"");

WriteLiteral(">");

            
            #line 24 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                             Write(Html.Raw(Model.Count));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Width\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Width\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">宽度：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Width\"");

WriteLiteral(">");

            
            #line 25 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                             Write(Html.Raw(Model.Width));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Height\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Height\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">高度：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Height\"");

WriteLiteral(">");

            
            #line 26 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                                Write(Html.Raw(Model.Height));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_PositionLeft\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_PositionLeft\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">距左距离：</td><td>&nbsp;<span");

WriteLiteral(" id=\"PositionLeft\"");

WriteLiteral(">");

            
            #line 27 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                                                    Write(Html.Raw(Model.PositionLeft));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_PositionTop\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_PositionTop\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">距顶距离：</td><td>&nbsp;<span");

WriteLiteral(" id=\"PositionTop\"");

WriteLiteral(">");

            
            #line 28 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                                                 Write(Html.Raw(Model.PositionTop));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Velocity\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Velocity\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">浮动速度：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Velocity\"");

WriteLiteral(">");

            
            #line 29 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                                        Write(Html.Raw(Model.Velocity));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_CityID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_CityID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">所属站点：</td><td>&nbsp;<span");

WriteLiteral(" id=\"CityID\"");

WriteLiteral(">");

            
            #line 30 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
                                                                                                  Write(Html.Raw(Model.CityID));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 34 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
   Write(RenderPage("~/Areas/PortalIPS/Views/Advertisement/Extend/Model_ViewHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        关闭\r\n    </a>\r\n</div>\r\n");

            
            #line 42 "..\..\Areas\PortalIPS\Views\Advertisement\_\Show.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/Advertisement/Extend/Model_ViewJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
