#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 22 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 23 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
    using System.Text;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.PortalIPS;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PortalIPS/Views/Category/_/AsyncTreeGrid.cshtml")]
    public partial class _Areas_PortalIPS_Views_Category___AsyncTreeGrid_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_PortalIPS_Views_Category___AsyncTreeGrid_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 3 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tt\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"toolbar\"");

WriteLiteral(" style=\"padding: 5px; height: auto\"");

WriteLiteral(">\r\n");

            
            #line 18 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
     foreach (ToolBar tool in ViewBag.ToolbarList)
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteAttribute("id", Tuple.Create(" id=\"", 559), Tuple.Create("\"", 581)
            
            #line 20 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
, Tuple.Create(Tuple.Create("", 564), Tuple.Create<System.Object, System.Int32>(tool.ToolBarID
            
            #line default
            #line hidden
, 564), false)
);

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteAttribute("iconcls", Tuple.Create(" iconcls=\"", 608), Tuple.Create("\"", 635)
            
            #line 20 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
             , Tuple.Create(Tuple.Create("", 618), Tuple.Create<System.Object, System.Int32>(tool.ClassName
            
            #line default
            #line hidden
, 618), false)
);

WriteLiteral(" plain=\"true\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 649), Tuple.Create("\"", 723)
, Tuple.Create(Tuple.Create("", 659), Tuple.Create("T_", 659), true)
            
            #line 20 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 661), Tuple.Create<System.Object, System.Int32>(tool.ToolBarID.Replace("-","")
            
            #line default
            #line hidden
, 661), false)
, Tuple.Create(Tuple.Create("", 694), Tuple.Create("ClickHandler();return", 694), true)
, Tuple.Create(Tuple.Create(" ", 715), Tuple.Create("false;", 716), true)
, Tuple.Create(Tuple.Create(" ", 722), Tuple.Create("", 722), true)
);

WriteLiteral(">");

            
            #line 20 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
                                                                                                                                                                                                  Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 21 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
}

            
            #line default
            #line hidden
DefineSection("scripts_toolbar", () => {

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n");

            
            #line 27 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
     foreach (ToolBar tool in ViewBag.ToolbarList)
    {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral(" function T_");

            
            #line 29 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
              Write(tool.ToolBarID.Replace("-",""));

            
            #line default
            #line hidden
WriteLiteral("ClickHandler() {\r\n");

WriteLiteral("    ");

WriteLiteral("     ");

            
            #line 30 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
      Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

WriteLiteral("     return false;\r\n");

WriteLiteral("    ");

WriteLiteral(" }\r\n");

            
            #line 33 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</script>\r\n");

});

WriteLiteral("</div>\r\n");

            
            #line 37 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/Category/Extend/Model_GridHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.query.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/TreeGridUtils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/SmartFormGrid.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var _baseUrl = '/PortalIPS/Category';
var _apiUrl = '/api/PortalIPS/Category';
var _pageUrl = '';
var Data = {
BaseUrl: _baseUrl,
ApiUrl: _apiUrl,
FilterID: 'Category_AppID',
DataUrl: _apiUrl + '/AsyncTreeGrid?'+_pageUrl,
CreateUrl: _baseUrl + '/Create?'+_pageUrl,
EditUrl: _baseUrl + '/Edit/{id}?'+_pageUrl,
ShowUrl: _baseUrl + '/Show/',
BatchDeleteUrl: _apiUrl + '/BatchDelete?'+_pageUrl,
DeleteUrl: _apiUrl + '/Delete?'+_pageUrl,
ModuleID: 'PortalIPS',
ModelID: 'Category',
PageSize: 20,
DialogWidth: 700,
DialogHeight: 600,
FieldShowType_Name_FieldName: 'CategoryName',
TreeField: 'CategoryName',
FieldShowType_Name_Title: '栏目名称',
ItemName: ""栏目管理"",
PrimaryKey: 'CategoryID',
SortField: 'OrderNum',
OrderType: 'asc',
Height: 0,
UnAutoLoadGrid: ");

            
            #line 70 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
            Write(RequestHelper.GetInt("UnAutoLoadGrid"));

            
            #line default
            #line hidden
WriteLiteral(",\r\ncolumns: [[\r\n");

            
            #line 72 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
 foreach (ToolBar tool in ViewBag.ToolbarColumnList)
{
    if(tool.OrderID < 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("{field: \'");

            
            #line 76 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
               Write(tool.ToolBarID);

            
            #line default
            #line hidden
WriteLiteral("\', title: \'");

            
            #line 76 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
                                           Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("\', sortable: false,width:");

            
            #line 76 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
                                                                                       Write(tool.ToolBarName.Length*15+10);

            
            #line default
            #line hidden
WriteLiteral(",align:\'center\',formatter: function(value, row, index){\r\n");

WriteLiteral("        ");

WriteLiteral("    ");

            
            #line 77 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
         Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

WriteLiteral("}},\r\n");

            
            #line 79 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral(@"
{field: 'ParentID', title: '父级ID', sortable: true,width:100,hidden:true,align:'left'},
{field: 'CategoryID', title: '栏目ID', sortable: true,width:100,hidden:true,align:'left'},
{field: 'IconName', title: '栏目标识', sortable: true,width:100,align:'left'},
{field: 'CategoryName', title: '栏目名称', sortable: true,width:300,align:'left'},
{field: 'DisplayName', title: '显示名称', sortable: true,width:100,align:'left'},
{field: 'BackNvarchar2_ShowValue', title: '栏目类型', sortable: true,width:100,align:'left'},
{field: 'C_ParentID_ShowValue', title: '父级栏目名称', sortable: true,width:100,hidden:true,align:'left'},
{field: 'CategoryInfoType_ShowValue', title: '信息类型', sortable: true,width:100,align:'left'},
{field: 'OrderNum', title: '排序ID', sortable: true,width:100,align:'left'},
{field: 'Flag_ShowValue', title: '是否启用', sortable: true,width:100,align:'left'},
{field: 'IsJournal_ShowValue', title: '栏目显示类型', sortable: true,width:100,align:'left'},
{field: 'BackNvarchar1_ShowValue', title: '是否需要发布', sortable: true,width:100,align:'left'},
{field: 'CategoryPath', title: '栏目路径', sortable: true,width:100,hidden:true,align:'left'}
");

            
            #line 95 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
 foreach (ToolBar tool in ViewBag.ToolbarColumnList)
{
    if(tool.OrderID >= 0)
    {

            
            #line default
            #line hidden
WriteLiteral(",{field: \'");

            
            #line 99 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
        Write(tool.ToolBarID);

            
            #line default
            #line hidden
WriteLiteral("\', title: \'");

            
            #line 99 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
                                    Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("\', sortable: false,width:");

            
            #line 99 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
                                                                                Write(tool.ToolBarName.Length*15+10);

            
            #line default
            #line hidden
WriteLiteral(",align:\'center\',formatter: function(value, row, index){\r\n");

WriteLiteral("    ");

            
            #line 100 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
 Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("}}\r\n");

            
            #line 102 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("]],\r\nfrozenColumns: [\r\n    [\r\n        {\r\n            field: \'ck\',\r\n            ch" +
"eckbox: true\r\n        }\r\n    ]\r\n],\r\ntoolbar: \'#toolbar\',\r\nsingleSelect: ");

            
            #line 114 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
          Write(RequestHelper.GetBool("SingleSelect",true).ToString().ToLower());

            
            #line default
            #line hidden
WriteLiteral("\r\n}\r\n        Data.treeField = \'CategoryName\';\r\n       \r\n        jQuery(function (" +
") {\r\n            jQuery(\'#toolbar\').append(\'<a id=\"btnRefresh\" href=\"javascript:" +
"void(0)\"  class=\"easyui-linkbutton\" iconcls=\"icon-reload\" plain=\"true\" onclick=\"" +
"ReloadData();return false; \">刷新</a>\');\r\n            jQuery(\'#btnRefresh\').linkbu" +
"tton();\r\n            window.onresize = setGridHeight;\r\n            jQuery(\'#tt\')" +
".treegrid({\r\n                iconCls: \'icon-save\',\r\n                url: Data.Da" +
"taUrl,\r\n                nowrap: true,\r\n                rownumbers: true,\r\n      " +
"          animate: true,\r\n                collapsible: true,\r\n                id" +
"Field: Data.PrimaryKey,\r\n                treeField: Data.TreeField,\r\n           " +
"     onBeforeLoad: function (row, param) {\r\n                    jQuery(this).tre" +
"egrid(\'unselectAll\');\r\n                    if (row) {\r\n                        j" +
"Query(this).treegrid(\'options\').url =Data.DataUrl+\'&ParentID=\'\r\n                " +
"            + row[Data.PrimaryKey];\r\n                    } else {\r\n             " +
"           jQuery(this).treegrid(\'options\').url = Data.DataUrl;\r\n               " +
"     }\r\n                },\r\n                onLoadError: function () {\r\n        " +
"            jQuery.messager.alert(\'加载数据出错\', \"加载数据出错\", \'error\');\r\n               " +
" },\r\n                onDblClickRow: function (row) {\r\n                    OpenDi" +
"alog_ViewFormByID(row[Data.PrimaryKey]);\r\n                },\r\n                on" +
"LoadSuccess: function (row, data) {\r\n                    if (data.total == \"-1\")" +
" {\r\n                        jQuery.messager.alert(\'加载数据出错\', data.msg, \'error\');\r" +
"\n                    }\r\n                },\r\n                columns: Data.column" +
"s,\r\n                toolbar: Data.toolbar\r\n            });\r\n            setGridH" +
"eight();\r\n        });\r\n    </script>\r\n");

            
            #line 157 "..\..\Areas\PortalIPS\Views\Category\_\AsyncTreeGrid.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/Category/Extend/Model_GridJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
