#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.PortalIPS;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PortalIPS/Views/Category/_/Create.cshtml")]
    public partial class _Areas_PortalIPS_Views_Category___Create_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_PortalIPS_Views_Category___Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="新建栏目管理";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/PortalIPS/Category/Create\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_C_ParentID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_C_ParentID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">父级栏目名称：</td><td>&nbsp;\r\n\r\n<input");

WriteLiteral(" id=\"C_ParentID\"");

WriteLiteral(" name=\"C_ParentID\"");

WriteAttribute("url", Tuple.Create(" url=\"", 854), Tuple.Create("\"", 929)
, Tuple.Create(Tuple.Create("", 860), Tuple.Create("/api/PortalIPS/Category/EditTree?&iscombo=1&Value=", 860), true)
            
            #line 22 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
                  , Tuple.Create(Tuple.Create("", 910), Tuple.Create<System.Object, System.Int32>(Model.C_ParentID
            
            #line default
            #line hidden
, 910), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 930), Tuple.Create("\"", 957)
            
            #line 22 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
                                              , Tuple.Create(Tuple.Create("", 938), Tuple.Create<System.Object, System.Int32>(Model.C_ParentID
            
            #line default
            #line hidden
, 938), false)
);

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var C_ParentID_Value = \'");

            
            #line 24 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
                        Write(Model.C_ParentID);

            
            #line default
            #line hidden
WriteLiteral(@"';
    jQuery(function() {
        jQuery('#C_ParentID').combotree(
        {
            onLoadSuccess:function(node, data) {
                jQuery('#C_ParentID').combotree('setValue',C_ParentID_Value);
            }
        });
    });
</script>
</td></tr>
<tr");

WriteLiteral(" id=\"Container_CategoryName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_CategoryName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目名称：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CategoryName\"");

WriteLiteral(" name=\"CategoryName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1489), Tuple.Create("\"", 1518)
            
            #line 36 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1497), Tuple.Create<System.Object, System.Int32>(Model.CategoryName
            
            #line default
            #line hidden
, 1497), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_DisplayName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_DisplayName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">显示名称：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DisplayName\"");

WriteLiteral(" name=\"DisplayName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1773), Tuple.Create("\"", 1801)
            
            #line 39 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1781), Tuple.Create<System.Object, System.Int32>(Model.DisplayName
            
            #line default
            #line hidden
, 1781), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackNvarchar2\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_BackNvarchar2\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目类型：</td><td>&nbsp;\r\n");

            
            #line 42 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_BackNvarchar2, "BackNvarchar2", Model.BackNvarchar2, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IsJournal\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IsJournal\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目显示类型：</td><td>&nbsp;\r\n");

            
            #line 45 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_IsJournal, "IsJournal", Model.IsJournal, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_CategoryInfoType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_CategoryInfoType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">信息类型：</td><td>&nbsp;\r\n");

            
            #line 48 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_CategoryInfoType, "CategoryInfoType", Model.CategoryInfoType, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_OrderNum\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_OrderNum\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">排序ID：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"OrderNum\"");

WriteLiteral(" name=\"OrderNum\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2758), Tuple.Create("\"", 2783)
            
            #line 51 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2766), Tuple.Create<System.Object, System.Int32>(Model.OrderNum
            
            #line default
            #line hidden
, 2766), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IconName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IconName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目标识：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"IconName\"");

WriteLiteral(" name=\"IconName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3025), Tuple.Create("\"", 3050)
            
            #line 54 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3033), Tuple.Create<System.Object, System.Int32>(Model.IconName
            
            #line default
            #line hidden
, 3033), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"500\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n<span");

WriteLiteral(" title=\"每站点对应的标识\"");

WriteLiteral("  class=\"easyui-tooltip\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'icon-help\'\"");

WriteLiteral("></a></span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IconPath\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IconPath\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目图片：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"IconPath\"");

WriteLiteral(" name=\"IconPath\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3436), Tuple.Create("\"", 3461)
            
            #line 57 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3444), Tuple.Create<System.Object, System.Int32>(Model.IconPath
            
            #line default
            #line hidden
, 3444), false)
);

WriteLiteral("   class=\"easyui-validatebox\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral("/>\r\n<br/>\r\n<input");

WriteLiteral(" class=\"easyui-filebox\"");

WriteLiteral(" data-options=\"buttonText:\'浏览\',accept: \'image/*\',buttonAlign:\'left\'\"");

WriteLiteral(" id=\"Upload_IconPath\"");

WriteLiteral(" name=\"Upload_IconPath\"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(" />\r\n<input");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnIconPath_Upload\"");

WriteLiteral(" name=\"btnIconPath_Upload\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" onclick=\"btnIconPath_UploadClick()\"");

WriteLiteral("/>\r\n");

            
            #line 61 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
 if(!string.IsNullOrEmpty(Model.IconPath)){

            
            #line default
            #line hidden
WriteLiteral(" <br/>");

WriteLiteral("<img");

WriteLiteral(" id=\"Preview_IconPath\"");

WriteAttribute("src", Tuple.Create(" src=\"", 3914), Tuple.Create("\"", 3937)
            
            #line 62 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3920), Tuple.Create<System.Object, System.Int32>(Model.IconPath
            
            #line default
            #line hidden
, 3920), false)
);

WriteLiteral(" style=\"height: 60px; \"");

WriteLiteral("/>\r\n");

            
            #line 63 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
}else{

            
            #line default
            #line hidden
WriteLiteral(" <br/>");

WriteLiteral("<img");

WriteLiteral(" id=\"Preview_IconPath\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4005), Tuple.Create("\"", 4028)
            
            #line 64 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4011), Tuple.Create<System.Object, System.Int32>(Model.IconPath
            
            #line default
            #line hidden
, 4011), false)
);

WriteLiteral(" style=\"height: 60px; display: none; \"");

WriteLiteral("/>\r\n");

            
            #line 65 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
 }

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    ///上传按钮事件
    function btnIconPath_UploadClick(){
        jQuery(""#myForm"").ajaxSubmit( {
            type: 'post',
            dataType: 'text',
            url: ""/api/SiteManage/UploadImage/Upload?FieldName=IconPath&UploadFieldName=Upload_IconPath&ModelID=Category&ModuleID=PortalIPS"",
            beforeSubmit: function(formData, jqForm, options) {
                var queryString = jQuery.param(formData);
                if( jQuery(""Upload_IconPath"").val()==""""){
                    alert(""请选择你要上传的图片！"");
                }
                return true;
            },
            success: function(msg) {
                eval(""var result=""+msg);
                if(result.Status==1){
                    jQuery(""#IconPath"").val(result.returnValue);
                    alert(""上传成功!"");
                    $('#Upload_IconPath').filebox('clear');
                    $('#Preview_IconPath').attr('src',result.returnValue);
                }else{
                    alert(result.returnValue);
                }
            },
            error: function(error) {
            }
        });
    }
</script>
</td></tr>
<tr");

WriteLiteral(" id=\"Container_Flag\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Flag\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否启用：</td><td>&nbsp;\r\n");

            
            #line 98 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_Flag, "Flag", Model.Flag, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackNvarchar\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_BackNvarchar\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">映射栏目编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"BackNvarchar\"");

WriteLiteral(" name=\"BackNvarchar\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5609), Tuple.Create("\"", 5638)
            
            #line 101 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5617), Tuple.Create<System.Object, System.Int32>(Model.BackNvarchar
            
            #line default
            #line hidden
, 5617), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackNvarchar1\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_BackNvarchar1\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否需要发布：</td><td>&nbsp;\r\n");

            
            #line 104 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_BackNvarchar1, "BackNvarchar1", Model.BackNvarchar1, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_CategoryPath\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_CategoryPath\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目路径：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CategoryPath\"");

WriteLiteral(" name=\"CategoryPath\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6122), Tuple.Create("\"", 6151)
            
            #line 107 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6130), Tuple.Create<System.Object, System.Int32>(Model.CategoryPath
            
            #line default
            #line hidden
, 6130), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n<span");

WriteLiteral(" class=\"tips\"");

WriteLiteral(">栏目名称拼音首字母</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_TemplatePath\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_TemplatePath\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">模板目录：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TemplatePath\"");

WriteLiteral(" name=\"TemplatePath\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6445), Tuple.Create("\"", 6474)
            
            #line 110 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6453), Tuple.Create<System.Object, System.Int32>(Model.TemplatePath
            
            #line default
            #line hidden
, 6453), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IndexTemplate\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IndexTemplate\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目主页模板：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"IndexTemplate\"");

WriteLiteral(" name=\"IndexTemplate\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6723), Tuple.Create("\"", 6753)
            
            #line 113 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6731), Tuple.Create<System.Object, System.Int32>(Model.IndexTemplate
            
            #line default
            #line hidden
, 6731), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ListTemplate\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ListTemplate\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目列表页模板：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ListTemplate\"");

WriteLiteral(" name=\"ListTemplate\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6999), Tuple.Create("\"", 7028)
            
            #line 116 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7007), Tuple.Create<System.Object, System.Int32>(Model.ListTemplate
            
            #line default
            #line hidden
, 7007), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_DetailTemplate\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_DetailTemplate\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目详细页模板：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DetailTemplate\"");

WriteLiteral(" name=\"DetailTemplate\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7282), Tuple.Create("\"", 7313)
            
            #line 119 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7290), Tuple.Create<System.Object, System.Int32>(Model.DetailTemplate
            
            #line default
            #line hidden
, 7290), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_LinkUrl\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_LinkUrl\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目导航地址：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"LinkUrl\"");

WriteLiteral(" name=\"LinkUrl\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:500px;height:40px\"");

WriteLiteral(">");

            
            #line 122 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
                                                                                              Write(Model.LinkUrl);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ManageLinkUrl\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ManageLinkUrl\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">后台链接地址：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"ManageLinkUrl\"");

WriteLiteral(" name=\"ManageLinkUrl\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:500px;height:40px\"");

WriteLiteral(">");

            
            #line 125 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
                                                                                                          Write(Model.ManageLinkUrl);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Description\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Description\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目描述：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"Description\"");

WriteLiteral(" name=\"Description\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:500px;height:80px\"");

WriteLiteral(">");

            
            #line 128 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
                                                                                                      Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IsTopMenuToPage\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IsTopMenuToPage\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否设为热门专题：</td><td>&nbsp;\r\n\r\n");

            
            #line 132 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_IsTopMenuToPage, "IsTopMenuToPage", Model.IsTopMenuToPage, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ParentID\"");

WriteLiteral("  name=\"ParentID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8443), Tuple.Create("\"", 8468)
            
            #line 134 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8451), Tuple.Create<System.Object, System.Int32>(Model.ParentID
            
            #line default
            #line hidden
, 8451), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"CategoryID\"");

WriteLiteral("  name=\"CategoryID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8526), Tuple.Create("\"", 8553)
            
            #line 134 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
                                                               , Tuple.Create(Tuple.Create("", 8534), Tuple.Create<System.Object, System.Int32>(Model.CategoryID
            
            #line default
            #line hidden
, 8534), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"CategoryType\"");

WriteLiteral("  name=\"CategoryType\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8615), Tuple.Create("\"", 8644)
            
            #line 134 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
                                                                                                                                                        , Tuple.Create(Tuple.Create("", 8623), Tuple.Create<System.Object, System.Int32>(Model.CategoryType
            
            #line default
            #line hidden
, 8623), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 137 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
   Write(RenderPage("~/Areas/PortalIPS/Views/Category/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        jQuery(function() {\r\n            CheckConditions();\r\njQuery(\'input[nam" +
"e=BackNvarchar2]\').bind(\'click\', CheckConditions);\r\nfunction CheckConditions(){\r" +
"\nif((IsInCheckBox(document.myForm.BackNvarchar2,\'多信息\')||IsInCheckBox(document.my" +
"Form.BackNvarchar2,\'单信息\')||IsInCheckBox(document.myForm.BackNvarchar2,\'专题栏目\'))){" +
"\r\njQuery(\'#Container_AppID\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_AppID\').hid" +
"e();\r\n} \r\nif((IsInCheckBox(document.myForm.BackNvarchar2,\'多信息\')||IsInCheckBox(do" +
"cument.myForm.BackNvarchar2,\'单信息\')||IsInCheckBox(document.myForm.BackNvarchar2,\'" +
"专题栏目\'))){\r\njQuery(\'#Container_BackInt\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_" +
"BackInt\').hide();\r\n} \r\nif(IsInCheckBox(document.myForm.BackNvarchar2,\'映射栏目\')){\r\n" +
"jQuery(\'#Container_BackNvarchar\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_BackNv" +
"archar\').hide();\r\n} \r\nif((IsInCheckBox(document.myForm.BackNvarchar2,\'多信息\')||IsI" +
"nCheckBox(document.myForm.BackNvarchar2,\'单信息\')||IsInCheckBox(document.myForm.Bac" +
"kNvarchar2,\'专题栏目\'))){\r\njQuery(\'#Container_BackNvarchar1\').show();\r\n} \r\nelse{ \r\nj" +
"Query(\'#Container_BackNvarchar1\').hide();\r\n} \r\nif((IsInCheckBox(document.myForm." +
"BackNvarchar2,\'多信息\')||IsInCheckBox(document.myForm.BackNvarchar2,\'单信息\')||IsInChe" +
"ckBox(document.myForm.BackNvarchar2,\'专题栏目\'))){\r\njQuery(\'#Container_DetailTemplat" +
"e\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_DetailTemplate\').hide();\r\n} \r\nif((Is" +
"InCheckBox(document.myForm.BackNvarchar2,\'多信息\')||IsInCheckBox(document.myForm.Ba" +
"ckNvarchar2,\'单信息\')||IsInCheckBox(document.myForm.BackNvarchar2,\'专题栏目\')||IsInChec" +
"kBox(document.myForm.BackNvarchar2,\'容器栏目\')||IsInCheckBox(document.myForm.BackNva" +
"rchar2,\'单页面\'))){\r\njQuery(\'#Container_IndexTemplate\').show();\r\n} \r\nelse{ \r\njQuery" +
"(\'#Container_IndexTemplate\').hide();\r\n} \r\nif((IsInCheckBox(document.myForm.BackN" +
"varchar2,\'多信息\')||IsInCheckBox(document.myForm.BackNvarchar2,\'单信息\')||IsInCheckBox" +
"(document.myForm.BackNvarchar2,\'专题栏目\'))){\r\njQuery(\'#Container_IsOpened\').show();" +
"\r\n} \r\nelse{ \r\njQuery(\'#Container_IsOpened\').hide();\r\n} \r\nif(IsInCheckBox(documen" +
"t.myForm.BackNvarchar2,\'外部链接\')){\r\njQuery(\'#Container_LinkUrl\').show();\r\n} \r\nelse" +
"{ \r\njQuery(\'#Container_LinkUrl\').hide();\r\n} \r\nif((IsInCheckBox(document.myForm.B" +
"ackNvarchar2,\'多信息\')||IsInCheckBox(document.myForm.BackNvarchar2,\'单信息\')||IsInChec" +
"kBox(document.myForm.BackNvarchar2,\'专题栏目\'))){\r\njQuery(\'#Container_ListTemplate\')" +
".show();\r\n} \r\nelse{ \r\njQuery(\'#Container_ListTemplate\').hide();\r\n} \r\njQuery(\'fie" +
"ldset\').show(); \r\njQuery(\"fieldset\").each(function(){ \r\nif(jQuery(\'tr\',this).len" +
"gth>0){\r\nif(jQuery(\'tr:visible\',this).length>0){jQuery(this).show()} else{jQuery" +
"(this).hide()}\r\n}\r\n});\r\n}\r\n;\r\n        });\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 220 "..\..\Areas\PortalIPS\Views\Category\_\Create.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/Category/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
