#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.PortalIPS;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PortalIPS/Views/Vote/_/Show.cshtml")]
    public partial class _Areas_PortalIPS_Views_Vote___Show_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_PortalIPS_Views_Vote___Show_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #F6F6F6; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/PortalIPS/Vote/Show\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_CategoryID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">所属栏目：</td><td>&nbsp;<span");

WriteLiteral(" id=\"CategoryID\"");

WriteLiteral(">");

            
            #line 19 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
                                                          Write(Html.Raw(Model.CategoryID));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">站点编号：</td><td>&nbsp;<span");

WriteLiteral(" id=\"AppID\"");

WriteLiteral(">");

            
            #line 20 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
                                                     Write(Html.Raw(Model.AppID));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_VoteName\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">投票主题：</td><td>&nbsp;<span");

WriteLiteral(" id=\"VoteName\"");

WriteLiteral(">");

            
            #line 23 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
                                                        Write(Html.Raw(Model.VoteName));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">状态：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Status\"");

WriteLiteral(">");

            
            #line 24 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
                                                    Write(Html.Raw(Model.Status_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_VoteContent\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">投票说明：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;<span");

WriteLiteral(" id=\"VoteContent\"");

WriteLiteral(">");

            
            #line 27 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
                                                                          Write(Html.Raw(Model.VoteContent));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_VoteCount\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">总票数：</td><td>&nbsp;<span");

WriteLiteral(" id=\"VoteCount\"");

WriteLiteral(">");

            
            #line 30 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
                                                        Write(Html.Raw(Model.VoteCount));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td>&nbsp;</td><td>&nbsp;</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_VoteItem\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">投票选项：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;<span");

WriteLiteral(" id=\"VoteItem\"");

WriteLiteral("><iframe");

WriteLiteral(" id=\"tab2Frame\"");

WriteLiteral(" name=\"tab2Frame\"");

WriteLiteral(" style=\"width:99%;height:300px\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1670), Tuple.Create("\"", 1797)
, Tuple.Create(Tuple.Create("", 1676), Tuple.Create("/SF/PortalIPS/VoteItem/GridView?VoteID=", 1676), true)
            
            #line 34 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
                                                                                                               , Tuple.Create(Tuple.Create("", 1715), Tuple.Create<System.Object, System.Int32>(Model.VoteID.Value
            
            #line default
            #line hidden
, 1715), false)
, Tuple.Create(Tuple.Create("", 1736), Tuple.Create("&AppID=", 1736), true)
            
            #line 34 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
                                                                                                                                           , Tuple.Create(Tuple.Create("", 1743), Tuple.Create<System.Object, System.Int32>(RequestHelper.GetString("AppID")
            
            #line default
            #line hidden
, 1743), false)
, Tuple.Create(Tuple.Create("", 1778), Tuple.Create("&Menu=VoteItem_List", 1778), true)
);

WriteLiteral(" frameborder=\"0\"");

WriteLiteral("></iframe></span></td>\r\n</tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
   Write(RenderPage("~/Areas/PortalIPS/Views/Vote/Extend/Model_ViewHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        关闭\r\n    </a>\r\n</div>\r\n");

            
            #line 47 "..\..\Areas\PortalIPS\Views\Vote\_\Show.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/Vote/Extend/Model_ViewJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
