#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.PortalIPS;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PortalIPS/Views/SMB_Information/_/Create.cshtml")]
    public partial class _Areas_PortalIPS_Views_SMB_Information___Create_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_PortalIPS_Views_SMB_Information___Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="新建信息内容";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/PortalIPS/SMB_Information/Create\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_CategoryID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">所属栏目：</td><td>&nbsp;\r\n<input");

WriteLiteral(" id=\"CategoryID\"");

WriteLiteral(" name=\"CategoryID\"");

WriteAttribute("url", Tuple.Create(" url=\"", 837), Tuple.Create("\"", 902)
, Tuple.Create(Tuple.Create("", 843), Tuple.Create("/api/PortalIPS/Category/EditTree?&Value=", 843), true)
            
            #line 22 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
        , Tuple.Create(Tuple.Create("", 883), Tuple.Create<System.Object, System.Int32>(Model.CategoryID
            
            #line default
            #line hidden
, 883), false)
);

WriteLiteral("  required=\"true\"");

WriteLiteral("   style=\"width:400px;\"");

WriteLiteral(" multiple=\"true\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" cascadeCheck=\"false\"");

WriteLiteral(" onlyLeafCheck=\"false\"");

WriteLiteral(">\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var CategoryID_Value = \'");

            
            #line 24 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                        Write(Model.CategoryID);

            
            #line default
            #line hidden
WriteLiteral(@"';
    jQuery(function() {
        jQuery('#CategoryID').combotree(
        {
            onLoadSuccess:function(node, data) {
                var arrValue=CategoryID_Value.split(',');
                jQuery('#CategoryID').combotree('setValues',arrValue);
            }
        });
    });
</script></td>
<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">信息类型：</td><td>&nbsp;\r\n");

            
            #line 36 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_InfoType, "InfoType", Model.InfoType, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackNvarchar2\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">文号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"BackNvarchar2\"");

WriteLiteral(" name=\"BackNvarchar2\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1711), Tuple.Create("\"", 1741)
            
            #line 41 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1719), Tuple.Create<System.Object, System.Int32>(Model.BackNvarchar2
            
            #line default
            #line hidden
, 1719), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"500\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">索引号：</td><td>&nbsp;<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"BackNvarchar3\"");

WriteLiteral("  name=\"BackNvarchar3\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1926), Tuple.Create("\"", 1956)
            
            #line 43 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                             , Tuple.Create(Tuple.Create("", 1934), Tuple.Create<System.Object, System.Int32>(Model.BackNvarchar3
            
            #line default
            #line hidden
, 1934), false)
);

WriteLiteral("/><span");

WriteLiteral(" id=\"BackNvarchar3_ShowValue\"");

WriteLiteral(">");

            
            #line 43 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                                                                                                    Write(Model.BackNvarchar3);

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Title\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">标题：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Title\"");

WriteLiteral(" name=\"Title\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2161), Tuple.Create("\"", 2183)
            
            #line 47 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2169), Tuple.Create<System.Object, System.Int32>(Model.Title
            
            #line default
            #line hidden
, 2169), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"255\"");

WriteLiteral(" style=\"width:70%\"");

WriteLiteral(" />\r\n<span");

WriteLiteral(" class=\"tips\"");

WriteLiteral(">建议不超过24个字符！</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_SubTitle\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">副标题：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SubTitle\"");

WriteLiteral(" name=\"SubTitle\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2460), Tuple.Create("\"", 2485)
            
            #line 52 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2468), Tuple.Create<System.Object, System.Int32>(Model.SubTitle
            
            #line default
            #line hidden
, 2468), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"1000\"");

WriteLiteral(" style=\"width:70%\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ShowTime\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">显示日期：</td><td>&nbsp;    <input");

WriteLiteral(" class=\"Wdate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onClick=\"WdatePicker({dateFmt:\'yyyy-MM-dd\'})\"");

WriteLiteral(" id=\"ShowTime\"");

WriteLiteral(" name=\"ShowTime\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2758), Tuple.Create("\"", 2793)
            
            #line 56 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                 , Tuple.Create(Tuple.Create("", 2766), Tuple.Create<System.Object, System.Int32>(Model.ShowTime_ShowValue
            
            #line default
            #line hidden
, 2766), false)
);

WriteLiteral(" style=\"width:120px;\"");

WriteLiteral(">\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">讲者：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Author\"");

WriteLiteral(" name=\"Author\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2909), Tuple.Create("\"", 2932)
            
            #line 59 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2917), Tuple.Create<System.Object, System.Int32>(Model.Author
            
            #line default
            #line hidden
, 2917), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Source\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">信息来源：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Source\"");

WriteLiteral(" name=\"Source\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3137), Tuple.Create("\"", 3160)
            
            #line 64 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3145), Tuple.Create<System.Object, System.Int32>(Model.Source
            
            #line default
            #line hidden
, 3145), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"255\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">关键字：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Keywords\"");

WriteLiteral(" name=\"Keywords\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3334), Tuple.Create("\"", 3359)
            
            #line 67 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3342), Tuple.Create<System.Object, System.Int32>(Model.Keywords
            
            #line default
            #line hidden
, 3342), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"255\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_MediaFileName\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">首页图片：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MediaFileName\"");

WriteLiteral(" name=\"MediaFileName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3601), Tuple.Create("\"", 3631)
            
            #line 72 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3609), Tuple.Create<System.Object, System.Int32>(Model.MediaFileName
            
            #line default
            #line hidden
, 3609), false)
);

WriteLiteral("   class=\"easyui-validatebox\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral("/>\r\n<br/>\r\n<input");

WriteLiteral(" class=\"easyui-filebox\"");

WriteLiteral(" data-options=\"buttonText:\'浏览\',accept: \'image/*\',buttonAlign:\'left\'\"");

WriteLiteral(" id=\"Upload_MediaFileName\"");

WriteLiteral(" name=\"Upload_MediaFileName\"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(" />\r\n<input");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnMediaFileName_Upload\"");

WriteLiteral(" name=\"btnMediaFileName_Upload\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" onclick=\"btnMediaFileName_UploadClick()\"");

WriteLiteral("/>\r\n<input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"ImageWater_MediaFileName\"");

WriteLiteral(" name=\"ImageWater_MediaFileName\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" />\r\n<label");

WriteLiteral(" for=\"ImageWater_MediaFileName\"");

WriteLiteral(">添加水印</label>\r\n");

            
            #line 78 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
 if(!string.IsNullOrEmpty(Model.MediaFileName)){

            
            #line default
            #line hidden
WriteLiteral(" <br/>");

WriteLiteral("<img");

WriteLiteral(" id=\"Preview_MediaFileName\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4270), Tuple.Create("\"", 4298)
            
            #line 79 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4276), Tuple.Create<System.Object, System.Int32>(Model.MediaFileName
            
            #line default
            #line hidden
, 4276), false)
);

WriteLiteral(" style=\"height: 60px; \"");

WriteLiteral("/>\r\n");

            
            #line 80 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
}else{

            
            #line default
            #line hidden
WriteLiteral(" <br/>");

WriteLiteral("<img");

WriteLiteral(" id=\"Preview_MediaFileName\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4371), Tuple.Create("\"", 4399)
            
            #line 81 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4377), Tuple.Create<System.Object, System.Int32>(Model.MediaFileName
            
            #line default
            #line hidden
, 4377), false)
);

WriteLiteral(" style=\"height: 60px; display: none; \"");

WriteLiteral("/>\r\n");

            
            #line 82 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
 }

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    ///上传按钮事件
    function btnMediaFileName_UploadClick(){
        jQuery(""#myForm"").ajaxSubmit( {
            type: 'post',
            dataType: 'text',
            url: ""/api/SiteManage/UploadImage/Upload?FieldName=MediaFileName&UploadFieldName=Upload_MediaFileName&ModelID=SMB_Information&ModuleID=PortalIPS"",
            beforeSubmit: function(formData, jqForm, options) {
                var queryString = jQuery.param(formData);
                if( jQuery(""Upload_MediaFileName"").val()==""""){
                    alert(""请选择你要上传的图片！"");
                }
                return true;
            },
            success: function(msg) {
                eval(""var result=""+msg);
                if(result.Status==1){
                    jQuery(""#MediaFileName"").val(result.returnValue);
                    alert(""上传成功!"");
                    $('#Upload_MediaFileName').filebox('clear');
                    $('#Preview_MediaFileName').attr('src',result.returnValue);
                }else{
                    alert(result.returnValue);
                }
            },
            error: function(error) {
            }
        });
    }
</script>
<span");

WriteLiteral(" class=\"tips\"");

WriteLiteral(">推荐尺寸：600×500</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_CreatorName\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">发布人：</td><td>&nbsp;<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"CreatorName\"");

WriteLiteral("  name=\"CreatorName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5841), Tuple.Create("\"", 5869)
            
            #line 116 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                         , Tuple.Create(Tuple.Create("", 5849), Tuple.Create<System.Object, System.Int32>(Model.CreatorName
            
            #line default
            #line hidden
, 5849), false)
);

WriteLiteral("/><span");

WriteLiteral(" id=\"CreatorName_ShowValue\"");

WriteLiteral(">");

            
            #line 116 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                                                                                            Write(Model.CreatorName);

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">发布部门：</td><td>&nbsp;<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"GroupName\"");

WriteLiteral("  name=\"GroupName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6032), Tuple.Create("\"", 6058)
            
            #line 117 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                      , Tuple.Create(Tuple.Create("", 6040), Tuple.Create<System.Object, System.Int32>(Model.GroupName
            
            #line default
            #line hidden
, 6040), false)
);

WriteLiteral("/><span");

WriteLiteral(" id=\"GroupName_ShowValue\"");

WriteLiteral(">");

            
            #line 117 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                                                                                     Write(Model.GroupName);

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Description\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">经文：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<textarea");

WriteLiteral(" id=\"Description\"");

WriteLiteral(" name=\"Description\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:95%;height:80px\"");

WriteLiteral(">");

            
            #line 121 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                                    Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackBoolean1\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">突出显示：</td><td>&nbsp;\r\n\r\n");

            
            #line 127 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_BackBoolean1, "BackBoolean1", Model.BackBoolean1, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">排序号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"BackInt\"");

WriteLiteral(" name=\"BackInt\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6666), Tuple.Create("\"", 6690)
            
            #line 130 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6674), Tuple.Create<System.Object, System.Int32>(Model.BackInt
            
            #line default
            #line hidden
, 6674), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"-10000\"");

WriteLiteral(" max=\"10000000\"");

WriteLiteral("  style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackNvarchar4\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">链接地址：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"BackNvarchar4\"");

WriteLiteral(" name=\"BackNvarchar4\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6934), Tuple.Create("\"", 6964)
            
            #line 135 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6942), Tuple.Create<System.Object, System.Int32>(Model.BackNvarchar4
            
            #line default
            #line hidden
, 6942), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"500\"");

WriteLiteral(" style=\"width:500px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackInt3\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否列表显示：</td><td>&nbsp;\r\n");

            
            #line 140 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_BackInt3, "BackInt3", Model.BackInt3, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td>\r\n<td>&nbsp;</td><td>&nbsp;</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_VideoUrl\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">视频音频地址：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"VideoUrl\"");

WriteLiteral(" name=\"VideoUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7425), Tuple.Create("\"", 7450)
            
            #line 146 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7433), Tuple.Create<System.Object, System.Int32>(Model.VideoUrl
            
            #line default
            #line hidden
, 7433), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"500\"");

WriteLiteral(" style=\"width:500px\"");

WriteLiteral(" />\r\n<span");

WriteLiteral(" title=\"视频直接输入地址，音频可上传\"");

WriteLiteral("  class=\"easyui-tooltip\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'icon-help\'\"");

WriteLiteral("></a></span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Content\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">内容：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<textarea");

WriteLiteral(" id=\"Content\"");

WriteLiteral(" name=\"Content\"");

WriteLiteral(" style=\"width:100%;height:500px\"");

WriteLiteral(">");

            
            #line 151 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                  Write(Model.Content);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n<script");

WriteLiteral(" src=\"/Resources/JsLib/ueditor/ueditor.config.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Resources/JsLib/ueditor/ueditor.all.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Resources/JsLib/ueditor/lang/zh-cn/zh-cn.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(function() {\r\n        UE.getEditor(\'Content\');\r\n    });\r\n</script></td>\r" +
"\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Attachment\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">附件：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;<iframe");

WriteLiteral(" id=\"tab2Frame\"");

WriteLiteral(" name=\"tab2Frame\"");

WriteLiteral(" style=\"width:99%;height:300px\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8350), Tuple.Create("\"", 8508)
, Tuple.Create(Tuple.Create("", 8356), Tuple.Create("/PortalIPS/Attachment/Grid1?InfoGuid=", 8356), true)
            
            #line 162 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                       , Tuple.Create(Tuple.Create("", 8393), Tuple.Create<System.Object, System.Int32>(Model.InfoGuid
            
            #line default
            #line hidden
, 8393), false)
, Tuple.Create(Tuple.Create("", 8410), Tuple.Create("&AppID=", 8410), true)
            
            #line 162 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                                               , Tuple.Create(Tuple.Create("", 8417), Tuple.Create<System.Object, System.Int32>(RequestHelper.GetString("AppID")
            
            #line default
            #line hidden
, 8417), false)
, Tuple.Create(Tuple.Create("", 8452), Tuple.Create("&Menu=95f050d0-b4fb-442f-8d76-2a88eb794627&IFrameDepth=0", 8452), true)
);

WriteLiteral(" frameborder=\"0\"");

WriteLiteral("></iframe></td>\r\n</tr>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"InfoGuid\"");

WriteLiteral("  name=\"InfoGuid\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8600), Tuple.Create("\"", 8625)
            
            #line 164 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8608), Tuple.Create<System.Object, System.Int32>(Model.InfoGuid
            
            #line default
            #line hidden
, 8608), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"AppID\"");

WriteLiteral("  name=\"AppID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8673), Tuple.Create("\"", 8695)
            
            #line 164 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                     , Tuple.Create(Tuple.Create("", 8681), Tuple.Create<System.Object, System.Int32>(Model.AppID
            
            #line default
            #line hidden
, 8681), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"Creator\"");

WriteLiteral("  name=\"Creator\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8747), Tuple.Create("\"", 8771)
            
            #line 164 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                                                               , Tuple.Create(Tuple.Create("", 8755), Tuple.Create<System.Object, System.Int32>(Model.Creator
            
            #line default
            #line hidden
, 8755), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"GroupID\"");

WriteLiteral("  name=\"GroupID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8823), Tuple.Create("\"", 8847)
            
            #line 164 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                                                                                                                                           , Tuple.Create(Tuple.Create("", 8831), Tuple.Create<System.Object, System.Int32>(Model.GroupID
            
            #line default
            #line hidden
, 8831), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"Status\"");

WriteLiteral("  name=\"Status\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8897), Tuple.Create("\"", 8920)
            
            #line 164 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                                                                                                                                                                                                                     , Tuple.Create(Tuple.Create("", 8905), Tuple.Create<System.Object, System.Int32>(Model.Status
            
            #line default
            #line hidden
, 8905), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"BackBoolean\"");

WriteLiteral("  name=\"BackBoolean\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8980), Tuple.Create("\"", 9008)
            
            #line 164 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
                                                                                                                                                                                                                                                                                                                                                                        , Tuple.Create(Tuple.Create("", 8988), Tuple.Create<System.Object, System.Int32>(Model.BackBoolean
            
            #line default
            #line hidden
, 8988), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 167 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
   Write(RenderPage("~/Areas/PortalIPS/Views/SMB_Information/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        jQuery(function() {\r\n            CheckConditions();\r\njQuery(\'input[nam" +
"e=InfoType]\').bind(\'click\', CheckConditions);\r\nfunction CheckConditions(){\r\nif(I" +
"sInCheckBox(document.myForm.InfoType,\'AttachmentInfo\')){\r\njQuery(\'#Container_Att" +
"achment\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_Attachment\').hide();\r\n} \r\nif(I" +
"sInCheckBox(document.myForm.InfoType,\'OpenInfo\')){\r\njQuery(\'#Container_BackNvarc" +
"har2\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_BackNvarchar2\').hide();\r\n} \r\nif(I" +
"sInCheckBox(document.myForm.InfoType,\'LinkInfo\')){\r\njQuery(\'#Container_BackNvarc" +
"har4\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_BackNvarchar4\').hide();\r\n} \r\nif((" +
"IsInCheckBox(document.myForm.InfoType,\'CommonInfo\')||IsInCheckBox(document.myFor" +
"m.InfoType,\'AttachmentInfo\')||IsInCheckBox(document.myForm.InfoType,\'OpenInfo\')|" +
"|IsInCheckBox(document.myForm.InfoType,\'VideoInfo\')||IsInCheckBox(document.myFor" +
"m.InfoType,\'audioInfo\'))){\r\njQuery(\'#Container_Content\').show();\r\n} \r\nelse{ \r\njQ" +
"uery(\'#Container_Content\').hide();\r\n} \r\nif((IsInCheckBox(document.myForm.InfoTyp" +
"e,\'CommonInfo\')||IsInCheckBox(document.myForm.InfoType,\'AttachmentInfo\')||IsInCh" +
"eckBox(document.myForm.InfoType,\'OpenInfo\')||IsInCheckBox(document.myForm.InfoTy" +
"pe,\'audioInfo\'))){\r\njQuery(\'#Container_Description\').show();\r\n} \r\nelse{ \r\njQuery" +
"(\'#Container_Description\').hide();\r\n} \r\nif(IsInCheckBox(document.myForm.InfoType" +
",\'OpenInfo\')){\r\njQuery(\'#Container_InfoGuid\').show();\r\n} \r\nelse{ \r\njQuery(\'#Cont" +
"ainer_InfoGuid\').hide();\r\n} \r\nif((IsInCheckBox(document.myForm.InfoType,\'CommonI" +
"nfo\')||IsInCheckBox(document.myForm.InfoType,\'audioInfo\'))){\r\njQuery(\'#Container" +
"_VideoUrl\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_VideoUrl\').hide();\r\n} \r\njQue" +
"ry(\'fieldset\').show(); \r\njQuery(\"fieldset\").each(function(){ \r\nif(jQuery(\'tr\',th" +
"is).length>0){\r\nif(jQuery(\'tr:visible\',this).length>0){jQuery(this).show()} else" +
"{jQuery(this).hide()}\r\n}\r\n});\r\n}\r\n;\r\n        });\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 238 "..\..\Areas\PortalIPS\Views\SMB_Information\_\Create.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/SMB_Information/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
