#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 24 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 25 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
    using System.Text;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.PortalIPS;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PortalIPS/Views/vwInfoCategory/_/Grid1.cshtml")]
    public partial class _Areas_PortalIPS_Views_vwInfoCategory___Grid1_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_PortalIPS_Views_vwInfoCategory___Grid1_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 3 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tt\"");

WriteLiteral("></div>\r\n");

            
            #line 17 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/vwInfoCategory/Extend/Model_GridHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"toolbar\"");

WriteLiteral(" style=\"padding: 5px; height: auto\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"searchForm\"");

WriteLiteral(" name=\"searchForm\"");

WriteLiteral(" action=\"\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
        
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
         foreach (ToolBar tool in ViewBag.ToolbarList)
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteAttribute("id", Tuple.Create(" id=\"", 717), Tuple.Create("\"", 739)
            
            #line 22 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
, Tuple.Create(Tuple.Create("", 722), Tuple.Create<System.Object, System.Int32>(tool.ToolBarID
            
            #line default
            #line hidden
, 722), false)
);

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteAttribute("iconcls", Tuple.Create(" iconcls=\"", 766), Tuple.Create("\"", 793)
            
            #line 22 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
             , Tuple.Create(Tuple.Create("", 776), Tuple.Create<System.Object, System.Int32>(tool.ClassName
            
            #line default
            #line hidden
, 776), false)
);

WriteLiteral(" plain=\"true\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 807), Tuple.Create("\"", 881)
, Tuple.Create(Tuple.Create("", 817), Tuple.Create("T_", 817), true)
            
            #line 22 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 819), Tuple.Create<System.Object, System.Int32>(tool.ToolBarID.Replace("-","")
            
            #line default
            #line hidden
, 819), false)
, Tuple.Create(Tuple.Create("", 852), Tuple.Create("ClickHandler();return", 852), true)
, Tuple.Create(Tuple.Create(" ", 873), Tuple.Create("false;", 874), true)
, Tuple.Create(Tuple.Create(" ", 880), Tuple.Create("", 880), true)
);

WriteLiteral(">");

            
            #line 22 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
                                                                                                                                                                                                  Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 23 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
}

            
            #line default
            #line hidden
DefineSection("scripts_toolbar", () => {

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
     foreach (ToolBar tool in ViewBag.ToolbarList)
    {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral(" function T_");

            
            #line 31 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
              Write(tool.ToolBarID.Replace("-",""));

            
            #line default
            #line hidden
WriteLiteral("ClickHandler() {\r\n");

WriteLiteral("    ");

WriteLiteral("     ");

            
            #line 32 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
      Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

WriteLiteral("     return false;\r\n");

WriteLiteral("    ");

WriteLiteral(" }\r\n");

            
            #line 35 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</script>\r\n");

});

WriteLiteral("\r\n        <span");

WriteLiteral(" id=\"span_Title\"");

WriteLiteral("  style=\"height:24px;display: inline-block;\"");

WriteLiteral(">标题：<input");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Title\"");

WriteLiteral(" name=\"Title\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"width:100px\"");

WriteLiteral(" /></span>\r\n<span");

WriteLiteral(" id=\"span_Status\"");

WriteLiteral("  style=\"height:24px;display: inline-block;\"");

WriteLiteral(">状态：\r\n<select");

WriteLiteral(" id=\"Status\"");

WriteLiteral(" class=\"easyui-combobox\"");

WriteLiteral(" name=\"Status\"");

WriteLiteral(" style=\"width: 120px;\"");

WriteLiteral(">\r\n<option");

WriteLiteral(" value=\"\"");

WriteLiteral(">请选择</option>\r\n");

            
            #line 43 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowSelectOptions(ViewBag.DAL.NameValue_Status, "")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</select></span>\r\n\r\n            <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-search\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">查询</a>\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" id=\"PagerButtons\"");

WriteLiteral("><label><input");

WriteLiteral(" id=\"BatchCheck\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" />多选</label></div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var _baseUrl = \'/PortalIPS/vwInfoCategory\';\r\nvar _apiUrl = \'/api/Porta" +
"lIPS/vwInfoCategory\';\r\nvar _pageUrl = \'&&CategoryID=");

            
            #line 55 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
                        Write(RequestHelper.GetString("CategoryID"));

            
            #line default
            #line hidden
WriteLiteral(@"';
var Data = {
BaseUrl: _baseUrl,
ApiUrl: _apiUrl,
FilterID: 'vwInfoCategory_CategoryID',
DataUrl: _apiUrl + '/Grid1?'+_pageUrl,
CreateUrl: _baseUrl + '/Create?'+_pageUrl,
EditUrl: _baseUrl + '/Edit/{id}?'+_pageUrl,
ShowUrl: _baseUrl + '/Show/',
BatchDeleteUrl: _apiUrl + '/BatchDelete?'+_pageUrl,
DeleteUrl: _apiUrl + '/Delete?'+_pageUrl,
ModuleID: 'PortalIPS',
ModelID: 'vwInfoCategory',
PageSize: 20,
DialogWidth: 900,
DialogHeight: 600,
FieldShowType_Name_FieldName: '',
TreeField: '',
FieldShowType_Name_Title: '',
ItemName: ""信息内容管理"",
PrimaryKey: 'ID',
SortField: 'CreateTime',
OrderType: 'desc',
Height: 0,
UnAutoLoadGrid: ");

            
            #line 79 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
            Write(RequestHelper.GetInt("UnAutoLoadGrid"));

            
            #line default
            #line hidden
WriteLiteral(",\r\ncolumns: [[\r\n");

            
            #line 81 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
 foreach (ToolBar tool in ViewBag.ToolbarColumnList)
{
    if(tool.OrderID < 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("{field: \'");

            
            #line 85 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
               Write(tool.ToolBarID);

            
            #line default
            #line hidden
WriteLiteral("\', title: \'");

            
            #line 85 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
                                           Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("\', sortable: false,width:");

            
            #line 85 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
                                                                                       Write(tool.ToolBarName.Length*15+10);

            
            #line default
            #line hidden
WriteLiteral(",align:\'center\',formatter: function(value, row, index){\r\n");

WriteLiteral("        ");

WriteLiteral("    ");

            
            #line 86 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
         Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

WriteLiteral("}},\r\n");

            
            #line 88 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral(@"
{field: 'ID', title: 'ID', sortable: true,width:100,hidden:true,align:'left'},
{field: 'InfoGuid', title: 'ID', sortable: true,width:60,hidden:true,align:'left'},
{field: 'BackBoolean1', title: '突出显示', sortable: true,width:100,hidden:true,align:'left'},
{field: 'CategoryName', title: '所属栏目', sortable: true,width:100,align:'left'},
{field: 'Title', title: '标题', sortable: true,width:300,align:'left'},
{field: 'ShowTime_ShowValue', title: '显示时间', sortable: true,width:100,align:'left'},
{field: 'BackInt', title: '排序', sortable: true,width:100,align:'left'},
{field: 'CategoryID', title: '栏目ID', sortable: true,width:100,hidden:true,align:'left'},
{field: 'CreatorName', title: '创建人', sortable: true,width:100,align:'left'},
{field: 'GroupName', title: '创建部门', sortable: true,width:100,align:'left'},
{field: 'LastModifyTime', title: '最后修改时间', sortable: true,width:100,align:'left'},
{field: 'AuditorName', title: '审核人', sortable: true,width:100,align:'left'},
{field: 'InfoType_ShowValue', title: '信息类型', sortable: true,width:100,align:'left'},
{field: 'Status_ShowValue', title: '状态', sortable: true,width:100,align:'left'}
");

            
            #line 105 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
 foreach (ToolBar tool in ViewBag.ToolbarColumnList)
{
    if(tool.OrderID >= 0)
    {

            
            #line default
            #line hidden
WriteLiteral(",{field: \'");

            
            #line 109 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
        Write(tool.ToolBarID);

            
            #line default
            #line hidden
WriteLiteral("\', title: \'");

            
            #line 109 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
                                    Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("\', sortable: false,width:");

            
            #line 109 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
                                                                                Write(tool.ToolBarName.Length*15+10);

            
            #line default
            #line hidden
WriteLiteral(",align:\'center\',formatter: function(value, row, index){\r\n");

WriteLiteral("    ");

            
            #line 110 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
 Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("}}\r\n");

            
            #line 112 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("]],\r\nfrozenColumns: [\r\n    [\r\n        {\r\n            field: \'ck\',\r\n            ch" +
"eckbox: true\r\n        }\r\n    ]\r\n],\r\ntoolbar: \'#toolbar\',\r\nsingleSelect: ");

            
            #line 124 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
          Write(RequestHelper.GetBool("SingleSelect",true).ToString().ToLower());

            
            #line default
            #line hidden
WriteLiteral("\r\n}\r\n    </script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.query.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/GridUtils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/SmartFormGrid.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Grid.js\"");

WriteLiteral("></script>\r\n");

            
            #line 132 "..\..\Areas\PortalIPS\Views\vwInfoCategory\_\Grid1.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/vwInfoCategory/Extend/Model_GridJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
