#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.PortalIPS;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/PortalIPS/Views/Attachment/_/Edit.cshtml")]
    public partial class _Areas_PortalIPS_Views_Attachment___Edit_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_PortalIPS_Views_Attachment___Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\PortalIPS\Views\Attachment\_\Edit.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="编辑附件";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/PortalIPS/Attachment/Edit\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_DisplayFileName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_DisplayFileName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">显示名称：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DisplayFileName\"");

WriteLiteral(" name=\"DisplayFileName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 880), Tuple.Create("\"", 912)
            
            #line 21 "..\..\Areas\PortalIPS\Views\Attachment\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 888), Tuple.Create<System.Object, System.Int32>(Model.DisplayFileName
            
            #line default
            #line hidden
, 888), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"255\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_PhysicalFileUrl\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_PhysicalFileUrl\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">文件访问地址：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"PhysicalFileUrl\"");

WriteLiteral(" name=\"PhysicalFileUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1186), Tuple.Create("\"", 1218)
            
            #line 24 "..\..\Areas\PortalIPS\Views\Attachment\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1194), Tuple.Create<System.Object, System.Int32>(Model.PhysicalFileUrl
            
            #line default
            #line hidden
, 1194), false)
);

WriteLiteral("  class=\"easyui-validatebox\"");

WriteLiteral(" style=\"width: \"");

WriteLiteral("/>&nbsp;\r\n<input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"Upload_PhysicalFileUrl\"");

WriteLiteral(" name=\"Upload_PhysicalFileUrl\"");

WriteLiteral(" />\r\n<input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnPhysicalFileUrl_Upload\"");

WriteLiteral(" name=\"btnPhysicalFileUrl_Upload\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" onclick=\"btnPhysicalFileUrl_UploadClick()\"");

WriteLiteral("/>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n       ///上传按钮事件\r\n       function btnPhysicalFileUrl_UploadClick(){\r\n         " +
"   jQuery(\"#myForm\").ajaxSubmit( {\r\n                type: \'post\',\r\n             " +
"   dataType: \'json\',\r\n                url: \"/api/SiteManage/UploadFile/Upload?Fi" +
"eldName=PhysicalFileUrl&UploadFieldName=Upload_PhysicalFileUrl&ModelID=Attachmen" +
"t&ModuleID=PortalIPS\",\r\n                beforeSubmit:  function(formData, jqForm" +
", options) {\r\n                    var queryString = jQuery.param(formData);\r\n   " +
"                 if( jQuery(\"Upload_PhysicalFileUrl\").val()==\"\"){\r\n             " +
"           alert(\"请选择你要上传的文件！\");\r\n                    }\r\n                    ret" +
"urn true;\r\n                },\r\n                success: function(result) {\r\n    " +
"              // alert(msg);\r\n                  // eval(\"var result=\"+msg);\r\n   " +
"                if(result.Status==1){\r\n                        jQuery(\"#Physical" +
"FileUrl\").val(result.returnValue);\r\n                        //deleteFile(\"Upload" +
"_PhysicalFileUrl\");\r\n                        alert(\"上传成功\")\r\n                   }" +
"else{\r\n                        alert(result.returnValue);\r\n                   }\r" +
"\n                },\r\n                error: function(error) {\r\n                 " +
"   //alert(error);\r\n                }\r\n           });\r\n        }\r\n       \r\n\r\n   " +
"         /**\r\n        * file,input type=file 的name\r\n        **/ \r\n        functi" +
"on deleteFile(file){\r\n           var ie = (navigator.appVersion.indexOf(\"MSIE\")!" +
"=-1);//IE \r\n           var ff = (navigator.userAgent.indexOf(\"Firefox\")!=-1);//F" +
"irefox \r\n\r\n           if(ie)\r\n            clearIEFileValue(jQuery(\"input[name=\"+" +
"file+\"]\")[0]);\r\n           else\r\n            jQuery(\"input[name=\"+file+\"]\").attr" +
"(\"value\",\"\"); //FF\r\n        }\r\n        //清空上传控件的值，obj为上传控件对象\r\n        function c" +
"learIEFileValue(obj) {\r\n            obj.select();\r\n            document.execComm" +
"and(\"delete\");\r\n        }\r\n</script></td></tr>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"AttachmentID\"");

WriteLiteral("  name=\"AttachmentID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3476), Tuple.Create("\"", 3505)
            
            #line 78 "..\..\Areas\PortalIPS\Views\Attachment\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3484), Tuple.Create<System.Object, System.Int32>(Model.AttachmentID
            
            #line default
            #line hidden
, 3484), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"DownloadCount\"");

WriteLiteral("  name=\"DownloadCount\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3569), Tuple.Create("\"", 3599)
            
            #line 78 "..\..\Areas\PortalIPS\Views\Attachment\_\Edit.cshtml"
                                                                                 , Tuple.Create(Tuple.Create("", 3577), Tuple.Create<System.Object, System.Int32>(Model.DownloadCount
            
            #line default
            #line hidden
, 3577), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"InfoGuid\"");

WriteLiteral("  name=\"InfoGuid\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3653), Tuple.Create("\"", 3678)
            
            #line 78 "..\..\Areas\PortalIPS\Views\Attachment\_\Edit.cshtml"
                                                                                                                                                                     , Tuple.Create(Tuple.Create("", 3661), Tuple.Create<System.Object, System.Int32>(Model.InfoGuid
            
            #line default
            #line hidden
, 3661), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 81 "..\..\Areas\PortalIPS\Views\Attachment\_\Edit.cshtml"
   Write(RenderPage("~/Areas/PortalIPS/Views/Attachment/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
function CheckConditions(){
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 109 "..\..\Areas\PortalIPS\Views\Attachment\_\Edit.cshtml"
Write(RenderPage("~/Areas/PortalIPS/Views/Attachment/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
